// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dut.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dut::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dut::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<16> dut::ap_ST_st1_fsm_0 = "1";
const sc_lv<16> dut::ap_ST_st2_fsm_1 = "10";
const sc_lv<16> dut::ap_ST_st3_fsm_2 = "100";
const sc_lv<16> dut::ap_ST_st4_fsm_3 = "1000";
const sc_lv<16> dut::ap_ST_st5_fsm_4 = "10000";
const sc_lv<16> dut::ap_ST_st6_fsm_5 = "100000";
const sc_lv<16> dut::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<16> dut::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<16> dut::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<16> dut::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<16> dut::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<16> dut::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<16> dut::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<16> dut::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<16> dut::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<16> dut::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<32> dut::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dut::ap_const_lv1_1 = "1";
const sc_lv<32> dut::ap_const_lv32_1 = "1";
const sc_lv<32> dut::ap_const_lv32_F = "1111";
const sc_lv<32> dut::ap_const_lv32_2 = "10";
const sc_lv<1> dut::ap_const_lv1_0 = "0";
const sc_lv<32> dut::ap_const_lv32_7 = "111";
const sc_lv<32> dut::ap_const_lv32_C = "1100";
const sc_lv<32> dut::ap_const_lv32_E = "1110";
const sc_lv<6> dut::ap_const_lv6_0 = "000000";
const sc_lv<32> dut::ap_const_lv32_8 = "1000";
const sc_lv<10> dut::ap_const_lv10_0 = "0000000000";
const sc_lv<32> dut::ap_const_lv32_B = "1011";
const sc_lv<32> dut::ap_const_lv32_D = "1101";
const sc_lv<32> dut::ap_const_lv32_A = "1010";
const sc_lv<32> dut::ap_const_lv32_9 = "1001";
const sc_lv<8> dut::ap_const_lv8_1 = "1";
const sc_lv<8> dut::ap_const_lv8_20 = "100000";
const sc_lv<8> dut::ap_const_lv8_40 = "1000000";
const sc_lv<4> dut::ap_const_lv4_5 = "101";
const sc_lv<4> dut::ap_const_lv4_3 = "11";
const sc_lv<6> dut::ap_const_lv6_31 = "110001";
const sc_lv<6> dut::ap_const_lv6_1 = "1";
const sc_lv<10> dut::ap_const_lv10_240 = "1001000000";
const sc_lv<10> dut::ap_const_lv10_1 = "1";

dut::dut(sc_module_name name) : sc_module(name), mVcdFile(0) {
    w_conv1_U = new dut_w_conv1("w_conv1_U");
    w_conv1_U->clk(ap_clk);
    w_conv1_U->reset(ap_rst);
    w_conv1_U->address0(grp_dut_perform_conv_fu_168_weight_address0);
    w_conv1_U->ce0(grp_dut_perform_conv_fu_168_weight_ce0);
    w_conv1_U->q0(w_conv1_q0);
    b_conv1_U = new dut_b_conv1("b_conv1_U");
    b_conv1_U->clk(ap_clk);
    b_conv1_U->reset(ap_rst);
    b_conv1_U->address0(grp_dut_perform_conv_fu_168_bias_address0);
    b_conv1_U->ce0(grp_dut_perform_conv_fu_168_bias_ce0);
    b_conv1_U->q0(b_conv1_q0);
    w_conv2_U = new dut_w_conv2("w_conv2_U");
    w_conv2_U->clk(ap_clk);
    w_conv2_U->reset(ap_rst);
    w_conv2_U->address0(grp_dut_perform_conv_fu_168_weight_address0);
    w_conv2_U->ce0(grp_dut_perform_conv_fu_168_weight_ce0);
    w_conv2_U->q0(w_conv2_q0);
    b_conv2_U = new dut_b_conv2("b_conv2_U");
    b_conv2_U->clk(ap_clk);
    b_conv2_U->reset(ap_rst);
    b_conv2_U->address0(grp_dut_perform_conv_fu_168_bias_address0);
    b_conv2_U->ce0(grp_dut_perform_conv_fu_168_bias_ce0);
    b_conv2_U->q0(b_conv2_q0);
    mem_conv1_U = new dut_mem_conv1("mem_conv1_U");
    mem_conv1_U->clk(ap_clk);
    mem_conv1_U->reset(ap_rst);
    mem_conv1_U->address0(mem_conv1_address0);
    mem_conv1_U->ce0(mem_conv1_ce0);
    mem_conv1_U->we0(mem_conv1_we0);
    mem_conv1_U->d0(mem_conv1_d0);
    mem_conv1_U->q0(mem_conv1_q0);
    mem_conv2_U = new dut_mem_conv1("mem_conv2_U");
    mem_conv2_U->clk(ap_clk);
    mem_conv2_U->reset(ap_rst);
    mem_conv2_U->address0(mem_conv2_address0);
    mem_conv2_U->ce0(mem_conv2_ce0);
    mem_conv2_U->we0(grp_dut_perform_conv_fu_168_output_r_we0);
    mem_conv2_U->d0(grp_dut_perform_conv_fu_168_output_r_d0);
    mem_conv2_U->q0(mem_conv2_q0);
    output_V_assign_U = new dut_output_V_assign("output_V_assign_U");
    output_V_assign_U->clk(ap_clk);
    output_V_assign_U->reset(ap_rst);
    output_V_assign_U->address0(output_V_assign_address0);
    output_V_assign_U->ce0(output_V_assign_ce0);
    output_V_assign_U->we0(output_V_assign_we0);
    output_V_assign_U->d0(output_V_assign_d0);
    output_V_assign_U->q0(output_V_assign_q0);
    grp_dut_perform_conv_fu_168 = new dut_perform_conv("grp_dut_perform_conv_fu_168");
    grp_dut_perform_conv_fu_168->ap_clk(ap_clk);
    grp_dut_perform_conv_fu_168->ap_rst(ap_rst);
    grp_dut_perform_conv_fu_168->ap_start(grp_dut_perform_conv_fu_168_ap_start);
    grp_dut_perform_conv_fu_168->ap_done(grp_dut_perform_conv_fu_168_ap_done);
    grp_dut_perform_conv_fu_168->ap_idle(grp_dut_perform_conv_fu_168_ap_idle);
    grp_dut_perform_conv_fu_168->ap_ready(grp_dut_perform_conv_fu_168_ap_ready);
    grp_dut_perform_conv_fu_168->input_r_address0(grp_dut_perform_conv_fu_168_input_r_address0);
    grp_dut_perform_conv_fu_168->input_r_ce0(grp_dut_perform_conv_fu_168_input_r_ce0);
    grp_dut_perform_conv_fu_168->input_r_q0(grp_dut_perform_conv_fu_168_input_r_q0);
    grp_dut_perform_conv_fu_168->output_r_address0(grp_dut_perform_conv_fu_168_output_r_address0);
    grp_dut_perform_conv_fu_168->output_r_ce0(grp_dut_perform_conv_fu_168_output_r_ce0);
    grp_dut_perform_conv_fu_168->output_r_we0(grp_dut_perform_conv_fu_168_output_r_we0);
    grp_dut_perform_conv_fu_168->output_r_d0(grp_dut_perform_conv_fu_168_output_r_d0);
    grp_dut_perform_conv_fu_168->output_r_q0(grp_dut_perform_conv_fu_168_output_r_q0);
    grp_dut_perform_conv_fu_168->weight_address0(grp_dut_perform_conv_fu_168_weight_address0);
    grp_dut_perform_conv_fu_168->weight_ce0(grp_dut_perform_conv_fu_168_weight_ce0);
    grp_dut_perform_conv_fu_168->weight_q0(grp_dut_perform_conv_fu_168_weight_q0);
    grp_dut_perform_conv_fu_168->bias_address0(grp_dut_perform_conv_fu_168_bias_address0);
    grp_dut_perform_conv_fu_168->bias_ce0(grp_dut_perform_conv_fu_168_bias_ce0);
    grp_dut_perform_conv_fu_168->bias_q0(grp_dut_perform_conv_fu_168_bias_q0);
    grp_dut_perform_conv_fu_168->M(grp_dut_perform_conv_fu_168_M);
    grp_dut_perform_conv_fu_168->N(grp_dut_perform_conv_fu_168_N);
    grp_dut_perform_conv_fu_168->O(grp_dut_perform_conv_fu_168_O);
    dut_uitofp_32ns_32_6_U11 = new dut_uitofp_32ns_32_6<1,6,32,32>("dut_uitofp_32ns_32_6_U11");
    dut_uitofp_32ns_32_6_U11->clk(ap_clk);
    dut_uitofp_32ns_32_6_U11->reset(ap_rst);
    dut_uitofp_32ns_32_6_U11->din0(grp_fu_189_p0);
    dut_uitofp_32ns_32_6_U11->ce(ap_var_for_const0);
    dut_uitofp_32ns_32_6_U11->dout(grp_fu_189_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( exitcond_fu_258_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( exitcond_fu_258_p2 );

    SC_METHOD(thread_ap_sig_102);
    sensitive << ( ap_start );
    sensitive << ( strm_in_V_V_empty_n );

    SC_METHOD(thread_ap_sig_116);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_131);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_140);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_156);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_223);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_233);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_243);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_261);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_269);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_31);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_87);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_96);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_269 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_261 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_233 );

    SC_METHOD(thread_ap_sig_cseq_ST_st13_fsm_12);
    sensitive << ( ap_sig_140 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_243 );

    SC_METHOD(thread_ap_sig_cseq_ST_st15_fsm_14);
    sensitive << ( ap_sig_156 );

    SC_METHOD(thread_ap_sig_cseq_ST_st16_fsm_15);
    sensitive << ( ap_sig_96 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_31 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_87 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_116 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_131 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_223 );

    SC_METHOD(thread_exitcond1_i_fu_207_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( bvh_d_index_reg_134 );

    SC_METHOD(thread_exitcond_fu_258_p2);
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( i_reg_157 );

    SC_METHOD(thread_exitcond_i_fu_236_p2);
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( i1_i_reg_146 );

    SC_METHOD(thread_grp_dut_perform_conv_fu_168_M);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_grp_dut_perform_conv_fu_168_N);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_grp_dut_perform_conv_fu_168_O);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_grp_dut_perform_conv_fu_168_ap_start);
    sensitive << ( ap_reg_grp_dut_perform_conv_fu_168_ap_start );

    SC_METHOD(thread_grp_dut_perform_conv_fu_168_bias_q0);
    sensitive << ( b_conv1_q0 );
    sensitive << ( b_conv2_q0 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_grp_dut_perform_conv_fu_168_input_r_q0);
    sensitive << ( mem_conv1_q0 );
    sensitive << ( mem_conv2_q0 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_grp_dut_perform_conv_fu_168_output_r_q0);
    sensitive << ( mem_conv1_q0 );
    sensitive << ( mem_conv2_q0 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_grp_dut_perform_conv_fu_168_weight_q0);
    sensitive << ( w_conv1_q0 );
    sensitive << ( w_conv2_q0 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_grp_fu_189_p0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_18_fu_219_p3 );

    SC_METHOD(thread_i_2_fu_264_p2);
    sensitive << ( i_reg_157 );

    SC_METHOD(thread_i_3_fu_213_p2);
    sensitive << ( bvh_d_index_reg_134 );

    SC_METHOD(thread_i_4_fu_242_p2);
    sensitive << ( i1_i_reg_146 );

    SC_METHOD(thread_index_assign_cast3_fu_203_p1);
    sensitive << ( bvh_d_index_reg_134 );

    SC_METHOD(thread_mem_conv1_address0);
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( tmp_30_i_fu_248_p1 );
    sensitive << ( grp_dut_perform_conv_fu_168_input_r_address0 );
    sensitive << ( grp_dut_perform_conv_fu_168_output_r_address0 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( tmp_29_i_fu_231_p1 );

    SC_METHOD(thread_mem_conv1_ce0);
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( grp_dut_perform_conv_fu_168_input_r_ce0 );
    sensitive << ( grp_dut_perform_conv_fu_168_output_r_ce0 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_mem_conv1_d0);
    sensitive << ( tmp_28_i_reg_298 );
    sensitive << ( grp_dut_perform_conv_fu_168_output_r_d0 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_mem_conv1_we0);
    sensitive << ( grp_dut_perform_conv_fu_168_output_r_we0 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_mem_conv2_address0);
    sensitive << ( grp_dut_perform_conv_fu_168_input_r_address0 );
    sensitive << ( grp_dut_perform_conv_fu_168_output_r_address0 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_mem_conv2_ce0);
    sensitive << ( grp_dut_perform_conv_fu_168_input_r_ce0 );
    sensitive << ( grp_dut_perform_conv_fu_168_output_r_ce0 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_output_V_assign_address0);
    sensitive << ( tmp_30_i_reg_311 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( tmp_fu_270_p1 );

    SC_METHOD(thread_output_V_assign_ce0);
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_output_V_assign_d0);
    sensitive << ( mem_conv1_q0 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_output_V_assign_we0);
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_p_Result_s_fu_196_p3);
    sensitive << ( tmp_V_2_reg_275 );
    sensitive << ( tmp_17_fu_192_p1 );

    SC_METHOD(thread_strm_in_V_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( strm_in_V_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_strm_in_V_V_read);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( strm_in_V_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_102 );

    SC_METHOD(thread_strm_out_V_V_blk_n);
    sensitive << ( strm_out_V_V_full_n );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );

    SC_METHOD(thread_strm_out_V_V_din);
    sensitive << ( strm_out_V_V_full_n );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( output_V_assign_q0 );

    SC_METHOD(thread_strm_out_V_V_write);
    sensitive << ( strm_out_V_V_full_n );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );

    SC_METHOD(thread_tmp_17_fu_192_p1);
    sensitive << ( strm_in_V_V_dout );

    SC_METHOD(thread_tmp_18_fu_219_p3);
    sensitive << ( p_Result_s_reg_280 );
    sensitive << ( index_assign_cast3_fu_203_p1 );

    SC_METHOD(thread_tmp_29_i_fu_231_p1);
    sensitive << ( bvh_d_index_reg_134 );

    SC_METHOD(thread_tmp_30_i_fu_248_p1);
    sensitive << ( i1_i_reg_146 );

    SC_METHOD(thread_tmp_fu_270_p1);
    sensitive << ( i_reg_157 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( strm_in_V_V_empty_n );
    sensitive << ( strm_out_V_V_full_n );
    sensitive << ( ap_sig_102 );
    sensitive << ( exitcond1_i_fu_207_p2 );
    sensitive << ( exitcond_i_fu_236_p2 );
    sensitive << ( exitcond_fu_258_p2 );
    sensitive << ( grp_dut_perform_conv_fu_168_ap_done );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000000000000001";
    ap_reg_grp_dut_perform_conv_fu_168_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dut_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, strm_in_V_V_dout, "(port)strm_in_V_V_dout");
    sc_trace(mVcdFile, strm_in_V_V_empty_n, "(port)strm_in_V_V_empty_n");
    sc_trace(mVcdFile, strm_in_V_V_read, "(port)strm_in_V_V_read");
    sc_trace(mVcdFile, strm_out_V_V_din, "(port)strm_out_V_V_din");
    sc_trace(mVcdFile, strm_out_V_V_full_n, "(port)strm_out_V_V_full_n");
    sc_trace(mVcdFile, strm_out_V_V_write, "(port)strm_out_V_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_31, "ap_sig_31");
    sc_trace(mVcdFile, w_conv1_q0, "w_conv1_q0");
    sc_trace(mVcdFile, b_conv1_q0, "b_conv1_q0");
    sc_trace(mVcdFile, w_conv2_q0, "w_conv2_q0");
    sc_trace(mVcdFile, b_conv2_q0, "b_conv2_q0");
    sc_trace(mVcdFile, strm_in_V_V_blk_n, "strm_in_V_V_blk_n");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_87, "ap_sig_87");
    sc_trace(mVcdFile, strm_out_V_V_blk_n, "strm_out_V_V_blk_n");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st16_fsm_15, "ap_sig_cseq_ST_st16_fsm_15");
    sc_trace(mVcdFile, ap_sig_96, "ap_sig_96");
    sc_trace(mVcdFile, tmp_V_2_reg_275, "tmp_V_2_reg_275");
    sc_trace(mVcdFile, ap_sig_102, "ap_sig_102");
    sc_trace(mVcdFile, p_Result_s_fu_196_p3, "p_Result_s_fu_196_p3");
    sc_trace(mVcdFile, p_Result_s_reg_280, "p_Result_s_reg_280");
    sc_trace(mVcdFile, i_3_fu_213_p2, "i_3_fu_213_p2");
    sc_trace(mVcdFile, i_3_reg_288, "i_3_reg_288");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_116, "ap_sig_116");
    sc_trace(mVcdFile, exitcond1_i_fu_207_p2, "exitcond1_i_fu_207_p2");
    sc_trace(mVcdFile, grp_fu_189_p1, "grp_fu_189_p1");
    sc_trace(mVcdFile, tmp_28_i_reg_298, "tmp_28_i_reg_298");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_131, "ap_sig_131");
    sc_trace(mVcdFile, i_4_fu_242_p2, "i_4_fu_242_p2");
    sc_trace(mVcdFile, i_4_reg_306, "i_4_reg_306");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st13_fsm_12, "ap_sig_cseq_ST_st13_fsm_12");
    sc_trace(mVcdFile, ap_sig_140, "ap_sig_140");
    sc_trace(mVcdFile, tmp_30_i_fu_248_p1, "tmp_30_i_fu_248_p1");
    sc_trace(mVcdFile, tmp_30_i_reg_311, "tmp_30_i_reg_311");
    sc_trace(mVcdFile, exitcond_i_fu_236_p2, "exitcond_i_fu_236_p2");
    sc_trace(mVcdFile, i_2_fu_264_p2, "i_2_fu_264_p2");
    sc_trace(mVcdFile, i_2_reg_324, "i_2_reg_324");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st15_fsm_14, "ap_sig_cseq_ST_st15_fsm_14");
    sc_trace(mVcdFile, ap_sig_156, "ap_sig_156");
    sc_trace(mVcdFile, exitcond_fu_258_p2, "exitcond_fu_258_p2");
    sc_trace(mVcdFile, mem_conv1_address0, "mem_conv1_address0");
    sc_trace(mVcdFile, mem_conv1_ce0, "mem_conv1_ce0");
    sc_trace(mVcdFile, mem_conv1_we0, "mem_conv1_we0");
    sc_trace(mVcdFile, mem_conv1_d0, "mem_conv1_d0");
    sc_trace(mVcdFile, mem_conv1_q0, "mem_conv1_q0");
    sc_trace(mVcdFile, mem_conv2_address0, "mem_conv2_address0");
    sc_trace(mVcdFile, mem_conv2_ce0, "mem_conv2_ce0");
    sc_trace(mVcdFile, mem_conv2_q0, "mem_conv2_q0");
    sc_trace(mVcdFile, output_V_assign_address0, "output_V_assign_address0");
    sc_trace(mVcdFile, output_V_assign_ce0, "output_V_assign_ce0");
    sc_trace(mVcdFile, output_V_assign_we0, "output_V_assign_we0");
    sc_trace(mVcdFile, output_V_assign_d0, "output_V_assign_d0");
    sc_trace(mVcdFile, output_V_assign_q0, "output_V_assign_q0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_ap_start, "grp_dut_perform_conv_fu_168_ap_start");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_ap_done, "grp_dut_perform_conv_fu_168_ap_done");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_ap_idle, "grp_dut_perform_conv_fu_168_ap_idle");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_ap_ready, "grp_dut_perform_conv_fu_168_ap_ready");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_input_r_address0, "grp_dut_perform_conv_fu_168_input_r_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_input_r_ce0, "grp_dut_perform_conv_fu_168_input_r_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_input_r_q0, "grp_dut_perform_conv_fu_168_input_r_q0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_output_r_address0, "grp_dut_perform_conv_fu_168_output_r_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_output_r_ce0, "grp_dut_perform_conv_fu_168_output_r_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_output_r_we0, "grp_dut_perform_conv_fu_168_output_r_we0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_output_r_d0, "grp_dut_perform_conv_fu_168_output_r_d0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_output_r_q0, "grp_dut_perform_conv_fu_168_output_r_q0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_weight_address0, "grp_dut_perform_conv_fu_168_weight_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_weight_ce0, "grp_dut_perform_conv_fu_168_weight_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_weight_q0, "grp_dut_perform_conv_fu_168_weight_q0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_bias_address0, "grp_dut_perform_conv_fu_168_bias_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_bias_ce0, "grp_dut_perform_conv_fu_168_bias_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_bias_q0, "grp_dut_perform_conv_fu_168_bias_q0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_M, "grp_dut_perform_conv_fu_168_M");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_N, "grp_dut_perform_conv_fu_168_N");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_168_O, "grp_dut_perform_conv_fu_168_O");
    sc_trace(mVcdFile, bvh_d_index_reg_134, "bvh_d_index_reg_134");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_223, "ap_sig_223");
    sc_trace(mVcdFile, i1_i_reg_146, "i1_i_reg_146");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_233, "ap_sig_233");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_243, "ap_sig_243");
    sc_trace(mVcdFile, i_reg_157, "i_reg_157");
    sc_trace(mVcdFile, ap_reg_grp_dut_perform_conv_fu_168_ap_start, "ap_reg_grp_dut_perform_conv_fu_168_ap_start");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_261, "ap_sig_261");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_269, "ap_sig_269");
    sc_trace(mVcdFile, tmp_29_i_fu_231_p1, "tmp_29_i_fu_231_p1");
    sc_trace(mVcdFile, tmp_fu_270_p1, "tmp_fu_270_p1");
    sc_trace(mVcdFile, grp_fu_189_p0, "grp_fu_189_p0");
    sc_trace(mVcdFile, tmp_17_fu_192_p1, "tmp_17_fu_192_p1");
    sc_trace(mVcdFile, index_assign_cast3_fu_203_p1, "index_assign_cast3_fu_203_p1");
    sc_trace(mVcdFile, tmp_18_fu_219_p3, "tmp_18_fu_219_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("dut.hdltvin.dat");
    mHdltvoutHandle.open("dut.hdltvout.dat");
}

dut::~dut() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete w_conv1_U;
    delete b_conv1_U;
    delete w_conv2_U;
    delete b_conv2_U;
    delete mem_conv1_U;
    delete mem_conv2_U;
    delete output_V_assign_U;
    delete grp_dut_perform_conv_fu_168;
    delete dut_uitofp_32ns_32_6_U11;
}

void dut::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void dut::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_dut_perform_conv_fu_168_ap_start = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
              !esl_seteq<1,1,1>(exitcond1_i_fu_207_p2.read(), ap_const_lv1_0)) || 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()))) {
            ap_reg_grp_dut_perform_conv_fu_168_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_dut_perform_conv_fu_168_ap_ready.read())) {
            ap_reg_grp_dut_perform_conv_fu_168_ap_start = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        bvh_d_index_reg_134 = i_3_reg_288.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(strm_in_V_V_empty_n.read(), ap_const_logic_0))) {
        bvh_d_index_reg_134 = ap_const_lv6_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        i1_i_reg_146 = i_4_reg_306.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) && 
                !esl_seteq<1,1,1>(ap_const_logic_0, grp_dut_perform_conv_fu_168_ap_done.read()))) {
        i1_i_reg_146 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_236_p2.read()))) {
        i_reg_157 = ap_const_lv10_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) && 
                !esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_0))) {
        i_reg_157 = i_2_reg_324.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        i_2_reg_324 = i_2_fu_264_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        i_3_reg_288 = i_3_fu_213_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        i_4_reg_306 = i_4_fu_242_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && !esl_seteq<1,1,1>(strm_in_V_V_empty_n.read(), ap_const_logic_0))) {
        p_Result_s_reg_280 = p_Result_s_fu_196_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        tmp_28_i_reg_298 = grp_fu_189_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_236_p2.read()))) {
        tmp_30_i_reg_311 = tmp_30_i_fu_248_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !ap_sig_102.read())) {
        tmp_V_2_reg_275 = strm_in_V_V_dout.read();
    }
}

void dut::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_258_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dut::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dut::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_258_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dut::thread_ap_sig_102() {
    ap_sig_102 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(strm_in_V_V_empty_n.read(), ap_const_logic_0));
}

void dut::thread_ap_sig_116() {
    ap_sig_116 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void dut::thread_ap_sig_131() {
    ap_sig_131 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void dut::thread_ap_sig_140() {
    ap_sig_140 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(12, 12));
}

void dut::thread_ap_sig_156() {
    ap_sig_156 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(14, 14));
}

void dut::thread_ap_sig_223() {
    ap_sig_223 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void dut::thread_ap_sig_233() {
    ap_sig_233 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void dut::thread_ap_sig_243() {
    ap_sig_243 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void dut::thread_ap_sig_261() {
    ap_sig_261 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void dut::thread_ap_sig_269() {
    ap_sig_269 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void dut::thread_ap_sig_31() {
    ap_sig_31 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void dut::thread_ap_sig_87() {
    ap_sig_87 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void dut::thread_ap_sig_96() {
    ap_sig_96 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(15, 15));
}

void dut::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_269.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void dut::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_261.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void dut::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_233.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void dut::thread_ap_sig_cseq_ST_st13_fsm_12() {
    if (ap_sig_140.read()) {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    }
}

void dut::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_243.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void dut::thread_ap_sig_cseq_ST_st15_fsm_14() {
    if (ap_sig_156.read()) {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    }
}

void dut::thread_ap_sig_cseq_ST_st16_fsm_15() {
    if (ap_sig_96.read()) {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_0;
    }
}

void dut::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_31.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void dut::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_87.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void dut::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_116.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void dut::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_131.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void dut::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_223.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void dut::thread_exitcond1_i_fu_207_p2() {
    exitcond1_i_fu_207_p2 = (!bvh_d_index_reg_134.read().is_01() || !ap_const_lv6_31.is_01())? sc_lv<1>(): sc_lv<1>(bvh_d_index_reg_134.read() == ap_const_lv6_31);
}

void dut::thread_exitcond_fu_258_p2() {
    exitcond_fu_258_p2 = (!i_reg_157.read().is_01() || !ap_const_lv10_240.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_157.read() == ap_const_lv10_240);
}

void dut::thread_exitcond_i_fu_236_p2() {
    exitcond_i_fu_236_p2 = (!i1_i_reg_146.read().is_01() || !ap_const_lv10_240.is_01())? sc_lv<1>(): sc_lv<1>(i1_i_reg_146.read() == ap_const_lv10_240);
}

void dut::thread_grp_dut_perform_conv_fu_168_M() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        grp_dut_perform_conv_fu_168_M = ap_const_lv8_20;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        grp_dut_perform_conv_fu_168_M = ap_const_lv8_1;
    } else {
        grp_dut_perform_conv_fu_168_M = "XXXXXXXX";
    }
}

void dut::thread_grp_dut_perform_conv_fu_168_N() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        grp_dut_perform_conv_fu_168_N = ap_const_lv8_40;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        grp_dut_perform_conv_fu_168_N = ap_const_lv8_20;
    } else {
        grp_dut_perform_conv_fu_168_N = "XXXXXXXX";
    }
}

void dut::thread_grp_dut_perform_conv_fu_168_O() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        grp_dut_perform_conv_fu_168_O = ap_const_lv4_3;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        grp_dut_perform_conv_fu_168_O = ap_const_lv4_5;
    } else {
        grp_dut_perform_conv_fu_168_O =  (sc_lv<4>) ("XXXX");
    }
}

void dut::thread_grp_dut_perform_conv_fu_168_ap_start() {
    grp_dut_perform_conv_fu_168_ap_start = ap_reg_grp_dut_perform_conv_fu_168_ap_start.read();
}

void dut::thread_grp_dut_perform_conv_fu_168_bias_q0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        grp_dut_perform_conv_fu_168_bias_q0 = b_conv2_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        grp_dut_perform_conv_fu_168_bias_q0 = b_conv1_q0.read();
    } else {
        grp_dut_perform_conv_fu_168_bias_q0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dut::thread_grp_dut_perform_conv_fu_168_input_r_q0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        grp_dut_perform_conv_fu_168_input_r_q0 = mem_conv2_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        grp_dut_perform_conv_fu_168_input_r_q0 = mem_conv1_q0.read();
    } else {
        grp_dut_perform_conv_fu_168_input_r_q0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dut::thread_grp_dut_perform_conv_fu_168_output_r_q0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        grp_dut_perform_conv_fu_168_output_r_q0 = mem_conv1_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        grp_dut_perform_conv_fu_168_output_r_q0 = mem_conv2_q0.read();
    } else {
        grp_dut_perform_conv_fu_168_output_r_q0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dut::thread_grp_dut_perform_conv_fu_168_weight_q0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        grp_dut_perform_conv_fu_168_weight_q0 = w_conv2_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        grp_dut_perform_conv_fu_168_weight_q0 = w_conv1_q0.read();
    } else {
        grp_dut_perform_conv_fu_168_weight_q0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dut::thread_grp_fu_189_p0() {
    grp_fu_189_p0 = esl_zext<32,1>(tmp_18_fu_219_p3.read());
}

void dut::thread_i_2_fu_264_p2() {
    i_2_fu_264_p2 = (!i_reg_157.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(i_reg_157.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void dut::thread_i_3_fu_213_p2() {
    i_3_fu_213_p2 = (!bvh_d_index_reg_134.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(bvh_d_index_reg_134.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void dut::thread_i_4_fu_242_p2() {
    i_4_fu_242_p2 = (!i1_i_reg_146.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(i1_i_reg_146.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void dut::thread_index_assign_cast3_fu_203_p1() {
    index_assign_cast3_fu_203_p1 = esl_zext<32,6>(bvh_d_index_reg_134.read());
}

void dut::thread_mem_conv1_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        mem_conv1_address0 =  (sc_lv<10>) (tmp_29_i_fu_231_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        mem_conv1_address0 =  (sc_lv<10>) (tmp_30_i_fu_248_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        mem_conv1_address0 = grp_dut_perform_conv_fu_168_output_r_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        mem_conv1_address0 = grp_dut_perform_conv_fu_168_input_r_address0.read();
    } else {
        mem_conv1_address0 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void dut::thread_mem_conv1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()))) {
        mem_conv1_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        mem_conv1_ce0 = grp_dut_perform_conv_fu_168_output_r_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        mem_conv1_ce0 = grp_dut_perform_conv_fu_168_input_r_ce0.read();
    } else {
        mem_conv1_ce0 = ap_const_logic_0;
    }
}

void dut::thread_mem_conv1_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        mem_conv1_d0 = tmp_28_i_reg_298.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        mem_conv1_d0 = grp_dut_perform_conv_fu_168_output_r_d0.read();
    } else {
        mem_conv1_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dut::thread_mem_conv1_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()))) {
        mem_conv1_we0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        mem_conv1_we0 = grp_dut_perform_conv_fu_168_output_r_we0.read();
    } else {
        mem_conv1_we0 = ap_const_logic_0;
    }
}

void dut::thread_mem_conv2_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        mem_conv2_address0 = grp_dut_perform_conv_fu_168_output_r_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        mem_conv2_address0 = grp_dut_perform_conv_fu_168_input_r_address0.read();
    } else {
        mem_conv2_address0 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void dut::thread_mem_conv2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        mem_conv2_ce0 = grp_dut_perform_conv_fu_168_output_r_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        mem_conv2_ce0 = grp_dut_perform_conv_fu_168_input_r_ce0.read();
    } else {
        mem_conv2_ce0 = sc_logic('X');
    }
}

void dut::thread_output_V_assign_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        output_V_assign_address0 =  (sc_lv<10>) (tmp_30_i_reg_311.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        output_V_assign_address0 =  (sc_lv<10>) (tmp_fu_270_p1.read());
    } else {
        output_V_assign_address0 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void dut::thread_output_V_assign_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        output_V_assign_ce0 = ap_const_logic_1;
    } else {
        output_V_assign_ce0 = ap_const_logic_0;
    }
}

void dut::thread_output_V_assign_d0() {
    output_V_assign_d0 = mem_conv1_q0.read();
}

void dut::thread_output_V_assign_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        output_V_assign_we0 = ap_const_logic_1;
    } else {
        output_V_assign_we0 = ap_const_logic_0;
    }
}

void dut::thread_p_Result_s_fu_196_p3() {
    p_Result_s_fu_196_p3 = esl_concat<17,32>(tmp_17_fu_192_p1.read(), tmp_V_2_reg_275.read());
}

void dut::thread_strm_in_V_V_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        strm_in_V_V_blk_n = strm_in_V_V_empty_n.read();
    } else {
        strm_in_V_V_blk_n = ap_const_logic_1;
    }
}

void dut::thread_strm_in_V_V_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !ap_sig_102.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(strm_in_V_V_empty_n.read(), ap_const_logic_0)))) {
        strm_in_V_V_read = ap_const_logic_1;
    } else {
        strm_in_V_V_read = ap_const_logic_0;
    }
}

void dut::thread_strm_out_V_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        strm_out_V_V_blk_n = strm_out_V_V_full_n.read();
    } else {
        strm_out_V_V_blk_n = ap_const_logic_1;
    }
}

void dut::thread_strm_out_V_V_din() {
    strm_out_V_V_din = output_V_assign_q0.read();
}

void dut::thread_strm_out_V_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) && 
         !esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_0))) {
        strm_out_V_V_write = ap_const_logic_1;
    } else {
        strm_out_V_V_write = ap_const_logic_0;
    }
}

void dut::thread_tmp_17_fu_192_p1() {
    tmp_17_fu_192_p1 = strm_in_V_V_dout.read().range(17-1, 0);
}

void dut::thread_tmp_18_fu_219_p3() {
    tmp_18_fu_219_p3 = (!index_assign_cast3_fu_203_p1.read().is_01() || sc_biguint<32>(index_assign_cast3_fu_203_p1.read()).to_uint() >= 49)? sc_lv<1>(): p_Result_s_reg_280.read().range(sc_biguint<32>(index_assign_cast3_fu_203_p1.read()).to_uint(), sc_biguint<32>(index_assign_cast3_fu_203_p1.read()).to_uint());
}

void dut::thread_tmp_29_i_fu_231_p1() {
    tmp_29_i_fu_231_p1 = esl_zext<64,6>(bvh_d_index_reg_134.read());
}

void dut::thread_tmp_30_i_fu_248_p1() {
    tmp_30_i_fu_248_p1 = esl_zext<64,10>(i1_i_reg_146.read());
}

void dut::thread_tmp_fu_270_p1() {
    tmp_fu_270_p1 = esl_zext<64,10>(i_reg_157.read());
}

void dut::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_102.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(strm_in_V_V_empty_n.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(exitcond1_i_fu_207_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st10_fsm_9;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 512 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_dut_perform_conv_fu_168_ap_done.read())) {
                ap_NS_fsm = ap_ST_st11_fsm_10;
            } else {
                ap_NS_fsm = ap_ST_st10_fsm_9;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 2048 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_dut_perform_conv_fu_168_ap_done.read())) {
                ap_NS_fsm = ap_ST_st13_fsm_12;
            } else {
                ap_NS_fsm = ap_ST_st12_fsm_11;
            }
            break;
        case 4096 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_236_p2.read())) {
                ap_NS_fsm = ap_ST_st15_fsm_14;
            } else {
                ap_NS_fsm = ap_ST_st14_fsm_13;
            }
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 16384 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_258_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st16_fsm_15;
            }
            break;
        case 32768 : 
            if (!esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st15_fsm_14;
            } else {
                ap_NS_fsm = ap_ST_st16_fsm_15;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
            break;
    }
}

void dut::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"strm_in_V_V_dout\" :  \"" << strm_in_V_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"strm_in_V_V_empty_n\" :  \"" << strm_in_V_V_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"strm_in_V_V_read\" :  \"" << strm_in_V_V_read.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"strm_out_V_V_din\" :  \"" << strm_out_V_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"strm_out_V_V_full_n\" :  \"" << strm_out_V_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"strm_out_V_V_write\" :  \"" << strm_out_V_V_write.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

