// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __dut_b_conv1_H__
#define __dut_b_conv1_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct dut_b_conv1_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 16;
  static const unsigned AddressRange = 64;
  static const unsigned AddressWidth = 6;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(dut_b_conv1_ram) {
        ram[0] = "0b0000011011110010";
        ram[1] = "0b0000011011101110";
        ram[2] = "0b0000100001000001";
        ram[3] = "0b0000011010110111";
        ram[4] = "0b0000101100001001";
        ram[5] = "0b0000011111011110";
        ram[6] = "0b0000011101011011";
        ram[7] = "0b0000100101010101";
        ram[8] = "0b0000101011111001";
        ram[9] = "0b0000011110010010";
        ram[10] = "0b0000011111100010";
        ram[11] = "0b0000011001011010";
        ram[12] = "0b0000100000011101";
        ram[13] = "0b0000100001011100";
        ram[14] = "0b0000011010110110";
        ram[15] = "0b0000010111011011";
        ram[16] = "0b0000011010010001";
        ram[17] = "0b0000011101110111";
        ram[18] = "0b0000010111001110";
        ram[19] = "0b0000011111100101";
        ram[20] = "0b0000100001001010";
        ram[21] = "0b0000100011110101";
        ram[22] = "0b0000011011010000";
        ram[23] = "0b0000011110001110";
        ram[24] = "0b0000011100101110";
        ram[25] = "0b0000011011100110";
        ram[26] = "0b0000101011100100";
        ram[27] = "0b0000011100000011";
        ram[28] = "0b0000011111101010";
        ram[29] = "0b0000011001011001";
        ram[30] = "0b0000100110010001";
        ram[31] = "0b0000011001101101";
        for (unsigned i = 32; i < 64 ; i = i + 1) {
            ram[i] = "0b0000000000000000";
        }


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(dut_b_conv1) {


static const unsigned DataWidth = 16;
static const unsigned AddressRange = 64;
static const unsigned AddressWidth = 6;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


dut_b_conv1_ram* meminst;


SC_CTOR(dut_b_conv1) {
meminst = new dut_b_conv1_ram("dut_b_conv1_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);


meminst->reset(reset);
meminst->clk(clk);
}
~dut_b_conv1() {
    delete meminst;
}


};//endmodule
#endif
