// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dut_cnn_xcel.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dut_cnn_xcel::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dut_cnn_xcel::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<14> dut_cnn_xcel::ap_ST_st1_fsm_0 = "1";
const sc_lv<14> dut_cnn_xcel::ap_ST_st2_fsm_1 = "10";
const sc_lv<14> dut_cnn_xcel::ap_ST_st3_fsm_2 = "100";
const sc_lv<14> dut_cnn_xcel::ap_ST_st4_fsm_3 = "1000";
const sc_lv<14> dut_cnn_xcel::ap_ST_st5_fsm_4 = "10000";
const sc_lv<14> dut_cnn_xcel::ap_ST_st6_fsm_5 = "100000";
const sc_lv<14> dut_cnn_xcel::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<14> dut_cnn_xcel::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<14> dut_cnn_xcel::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<14> dut_cnn_xcel::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<14> dut_cnn_xcel::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<14> dut_cnn_xcel::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<14> dut_cnn_xcel::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<14> dut_cnn_xcel::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<32> dut_cnn_xcel::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dut_cnn_xcel::ap_const_lv1_1 = "1";
const sc_lv<32> dut_cnn_xcel::ap_const_lv32_1 = "1";
const sc_lv<1> dut_cnn_xcel::ap_const_lv1_0 = "0";
const sc_lv<32> dut_cnn_xcel::ap_const_lv32_5 = "101";
const sc_lv<32> dut_cnn_xcel::ap_const_lv32_6 = "110";
const sc_lv<32> dut_cnn_xcel::ap_const_lv32_7 = "111";
const sc_lv<32> dut_cnn_xcel::ap_const_lv32_C = "1100";
const sc_lv<6> dut_cnn_xcel::ap_const_lv6_0 = "000000";
const sc_lv<13> dut_cnn_xcel::ap_const_lv13_0 = "0000000000000";
const sc_lv<10> dut_cnn_xcel::ap_const_lv10_0 = "0000000000";
const sc_lv<32> dut_cnn_xcel::ap_const_lv32_4 = "100";
const sc_lv<32> dut_cnn_xcel::ap_const_lv32_D = "1101";
const sc_lv<20> dut_cnn_xcel::ap_const_lv20_0 = "00000000000000000000";
const sc_lv<32> dut_cnn_xcel::ap_const_lv32_3 = "11";
const sc_lv<32> dut_cnn_xcel::ap_const_lv32_2 = "10";
const sc_lv<3> dut_cnn_xcel::ap_const_lv3_1 = "1";
const sc_lv<3> dut_cnn_xcel::ap_const_lv3_0 = "000";
const sc_lv<6> dut_cnn_xcel::ap_const_lv6_31 = "110001";
const sc_lv<6> dut_cnn_xcel::ap_const_lv6_1 = "1";
const sc_lv<12> dut_cnn_xcel::ap_const_lv12_0 = "000000000000";
const sc_lv<13> dut_cnn_xcel::ap_const_lv13_56 = "1010110";
const sc_lv<32> dut_cnn_xcel::ap_const_lv32_8 = "1000";
const sc_lv<6> dut_cnn_xcel::ap_const_lv6_3 = "11";
const sc_lv<10> dut_cnn_xcel::ap_const_lv10_240 = "1001000000";
const sc_lv<10> dut_cnn_xcel::ap_const_lv10_1 = "1";
const sc_lv<10> dut_cnn_xcel::ap_const_lv10_3 = "11";
const sc_lv<20> dut_cnn_xcel::ap_const_lv20_556 = "10101010110";
const sc_lv<32> dut_cnn_xcel::ap_const_lv32_13 = "10011";
const sc_lv<14> dut_cnn_xcel::ap_const_lv14_0 = "00000000000000";
const sc_lv<32> dut_cnn_xcel::ap_const_lv32_17 = "10111";
const sc_lv<32> dut_cnn_xcel::ap_const_lv32_1E = "11110";
const sc_lv<8> dut_cnn_xcel::ap_const_lv8_F4 = "11110100";

dut_cnn_xcel::dut_cnn_xcel(sc_module_name name) : sc_module(name), mVcdFile(0) {
    mem_conv1_0_V_U = new dut_cnn_xcel_mem_conv1_0_V("mem_conv1_0_V_U");
    mem_conv1_0_V_U->clk(ap_clk);
    mem_conv1_0_V_U->reset(ap_rst);
    mem_conv1_0_V_U->address0(mem_conv1_0_V_address0);
    mem_conv1_0_V_U->ce0(mem_conv1_0_V_ce0);
    mem_conv1_0_V_U->we0(mem_conv1_0_V_we0);
    mem_conv1_0_V_U->d0(mem_conv1_0_V_d0);
    mem_conv1_0_V_U->q0(mem_conv1_0_V_q0);
    mem_conv1_0_V_U->address1(grp_dut_perform_conv_fu_273_input_0_V_address1);
    mem_conv1_0_V_U->ce1(mem_conv1_0_V_ce1);
    mem_conv1_0_V_U->q1(mem_conv1_0_V_q1);
    mem_conv1_1_V_U = new dut_cnn_xcel_mem_conv1_0_V("mem_conv1_1_V_U");
    mem_conv1_1_V_U->clk(ap_clk);
    mem_conv1_1_V_U->reset(ap_rst);
    mem_conv1_1_V_U->address0(mem_conv1_1_V_address0);
    mem_conv1_1_V_U->ce0(mem_conv1_1_V_ce0);
    mem_conv1_1_V_U->we0(mem_conv1_1_V_we0);
    mem_conv1_1_V_U->d0(mem_conv1_1_V_d0);
    mem_conv1_1_V_U->q0(mem_conv1_1_V_q0);
    mem_conv1_1_V_U->address1(grp_dut_perform_conv_fu_273_input_1_V_address1);
    mem_conv1_1_V_U->ce1(mem_conv1_1_V_ce1);
    mem_conv1_1_V_U->q1(mem_conv1_1_V_q1);
    mem_conv1_2_V_U = new dut_cnn_xcel_mem_conv1_2_V("mem_conv1_2_V_U");
    mem_conv1_2_V_U->clk(ap_clk);
    mem_conv1_2_V_U->reset(ap_rst);
    mem_conv1_2_V_U->address0(mem_conv1_2_V_address0);
    mem_conv1_2_V_U->ce0(mem_conv1_2_V_ce0);
    mem_conv1_2_V_U->we0(mem_conv1_2_V_we0);
    mem_conv1_2_V_U->d0(mem_conv1_2_V_d0);
    mem_conv1_2_V_U->q0(mem_conv1_2_V_q0);
    mem_conv1_2_V_U->address1(grp_dut_perform_conv_fu_273_input_2_V_address1);
    mem_conv1_2_V_U->ce1(mem_conv1_2_V_ce1);
    mem_conv1_2_V_U->q1(mem_conv1_2_V_q1);
    mem_conv2_0_V_U = new dut_cnn_xcel_mem_conv2_0_V("mem_conv2_0_V_U");
    mem_conv2_0_V_U->clk(ap_clk);
    mem_conv2_0_V_U->reset(ap_rst);
    mem_conv2_0_V_U->address0(mem_conv2_0_V_address0);
    mem_conv2_0_V_U->ce0(mem_conv2_0_V_ce0);
    mem_conv2_0_V_U->we0(grp_dut_perform_conv_fu_273_output_0_V_we0);
    mem_conv2_0_V_U->d0(grp_dut_perform_conv_fu_273_output_0_V_d0);
    mem_conv2_0_V_U->q0(mem_conv2_0_V_q0);
    mem_conv2_0_V_U->address1(grp_dut_perform_conv_1_fu_257_input_V_address1);
    mem_conv2_0_V_U->ce1(mem_conv2_0_V_ce1);
    mem_conv2_0_V_U->q1(mem_conv2_0_V_q1);
    mem_conv2_1_V_U = new dut_cnn_xcel_mem_conv2_0_V("mem_conv2_1_V_U");
    mem_conv2_1_V_U->clk(ap_clk);
    mem_conv2_1_V_U->reset(ap_rst);
    mem_conv2_1_V_U->address0(mem_conv2_1_V_address0);
    mem_conv2_1_V_U->ce0(mem_conv2_1_V_ce0);
    mem_conv2_1_V_U->we0(grp_dut_perform_conv_fu_273_output_1_V_we0);
    mem_conv2_1_V_U->d0(grp_dut_perform_conv_fu_273_output_1_V_d0);
    mem_conv2_1_V_U->q0(mem_conv2_1_V_q0);
    mem_conv2_1_V_U->address1(grp_dut_perform_conv_1_fu_257_input_V1_address1);
    mem_conv2_1_V_U->ce1(mem_conv2_1_V_ce1);
    mem_conv2_1_V_U->q1(mem_conv2_1_V_q1);
    mem_conv2_2_V_U = new dut_cnn_xcel_mem_conv2_0_V("mem_conv2_2_V_U");
    mem_conv2_2_V_U->clk(ap_clk);
    mem_conv2_2_V_U->reset(ap_rst);
    mem_conv2_2_V_U->address0(mem_conv2_2_V_address0);
    mem_conv2_2_V_U->ce0(mem_conv2_2_V_ce0);
    mem_conv2_2_V_U->we0(grp_dut_perform_conv_fu_273_output_2_V_we0);
    mem_conv2_2_V_U->d0(grp_dut_perform_conv_fu_273_output_2_V_d0);
    mem_conv2_2_V_U->q0(mem_conv2_2_V_q0);
    mem_conv2_2_V_U->address1(grp_dut_perform_conv_1_fu_257_input_V2_address1);
    mem_conv2_2_V_U->ce1(mem_conv2_2_V_ce1);
    mem_conv2_2_V_U->q1(mem_conv2_2_V_q1);
    mem_conv2_3_V_U = new dut_cnn_xcel_mem_conv2_0_V("mem_conv2_3_V_U");
    mem_conv2_3_V_U->clk(ap_clk);
    mem_conv2_3_V_U->reset(ap_rst);
    mem_conv2_3_V_U->address0(mem_conv2_3_V_address0);
    mem_conv2_3_V_U->ce0(mem_conv2_3_V_ce0);
    mem_conv2_3_V_U->we0(grp_dut_perform_conv_fu_273_output_3_V_we0);
    mem_conv2_3_V_U->d0(grp_dut_perform_conv_fu_273_output_3_V_d0);
    mem_conv2_3_V_U->q0(mem_conv2_3_V_q0);
    mem_conv2_3_V_U->address1(grp_dut_perform_conv_1_fu_257_input_V3_address1);
    mem_conv2_3_V_U->ce1(mem_conv2_3_V_ce1);
    mem_conv2_3_V_U->q1(mem_conv2_3_V_q1);
    mem_conv2_4_V_U = new dut_cnn_xcel_mem_conv2_0_V("mem_conv2_4_V_U");
    mem_conv2_4_V_U->clk(ap_clk);
    mem_conv2_4_V_U->reset(ap_rst);
    mem_conv2_4_V_U->address0(mem_conv2_4_V_address0);
    mem_conv2_4_V_U->ce0(mem_conv2_4_V_ce0);
    mem_conv2_4_V_U->we0(grp_dut_perform_conv_fu_273_output_4_V_we0);
    mem_conv2_4_V_U->d0(grp_dut_perform_conv_fu_273_output_4_V_d0);
    mem_conv2_4_V_U->q0(mem_conv2_4_V_q0);
    mem_conv2_4_V_U->address1(grp_dut_perform_conv_1_fu_257_input_V4_address1);
    mem_conv2_4_V_U->ce1(mem_conv2_4_V_ce1);
    mem_conv2_4_V_U->q1(mem_conv2_4_V_q1);
    grp_dut_perform_conv_1_fu_257 = new dut_perform_conv_1("grp_dut_perform_conv_1_fu_257");
    grp_dut_perform_conv_1_fu_257->ap_clk(ap_clk);
    grp_dut_perform_conv_1_fu_257->ap_rst(ap_rst);
    grp_dut_perform_conv_1_fu_257->ap_start(grp_dut_perform_conv_1_fu_257_ap_start);
    grp_dut_perform_conv_1_fu_257->ap_done(grp_dut_perform_conv_1_fu_257_ap_done);
    grp_dut_perform_conv_1_fu_257->ap_idle(grp_dut_perform_conv_1_fu_257_ap_idle);
    grp_dut_perform_conv_1_fu_257->ap_ready(grp_dut_perform_conv_1_fu_257_ap_ready);
    grp_dut_perform_conv_1_fu_257->input_V_address0(grp_dut_perform_conv_1_fu_257_input_V_address0);
    grp_dut_perform_conv_1_fu_257->input_V_ce0(grp_dut_perform_conv_1_fu_257_input_V_ce0);
    grp_dut_perform_conv_1_fu_257->input_V_q0(mem_conv2_0_V_q0);
    grp_dut_perform_conv_1_fu_257->input_V_address1(grp_dut_perform_conv_1_fu_257_input_V_address1);
    grp_dut_perform_conv_1_fu_257->input_V_ce1(grp_dut_perform_conv_1_fu_257_input_V_ce1);
    grp_dut_perform_conv_1_fu_257->input_V_q1(mem_conv2_0_V_q1);
    grp_dut_perform_conv_1_fu_257->input_V1_address0(grp_dut_perform_conv_1_fu_257_input_V1_address0);
    grp_dut_perform_conv_1_fu_257->input_V1_ce0(grp_dut_perform_conv_1_fu_257_input_V1_ce0);
    grp_dut_perform_conv_1_fu_257->input_V1_q0(mem_conv2_1_V_q0);
    grp_dut_perform_conv_1_fu_257->input_V1_address1(grp_dut_perform_conv_1_fu_257_input_V1_address1);
    grp_dut_perform_conv_1_fu_257->input_V1_ce1(grp_dut_perform_conv_1_fu_257_input_V1_ce1);
    grp_dut_perform_conv_1_fu_257->input_V1_q1(mem_conv2_1_V_q1);
    grp_dut_perform_conv_1_fu_257->input_V2_address0(grp_dut_perform_conv_1_fu_257_input_V2_address0);
    grp_dut_perform_conv_1_fu_257->input_V2_ce0(grp_dut_perform_conv_1_fu_257_input_V2_ce0);
    grp_dut_perform_conv_1_fu_257->input_V2_q0(mem_conv2_2_V_q0);
    grp_dut_perform_conv_1_fu_257->input_V2_address1(grp_dut_perform_conv_1_fu_257_input_V2_address1);
    grp_dut_perform_conv_1_fu_257->input_V2_ce1(grp_dut_perform_conv_1_fu_257_input_V2_ce1);
    grp_dut_perform_conv_1_fu_257->input_V2_q1(mem_conv2_2_V_q1);
    grp_dut_perform_conv_1_fu_257->input_V3_address0(grp_dut_perform_conv_1_fu_257_input_V3_address0);
    grp_dut_perform_conv_1_fu_257->input_V3_ce0(grp_dut_perform_conv_1_fu_257_input_V3_ce0);
    grp_dut_perform_conv_1_fu_257->input_V3_q0(mem_conv2_3_V_q0);
    grp_dut_perform_conv_1_fu_257->input_V3_address1(grp_dut_perform_conv_1_fu_257_input_V3_address1);
    grp_dut_perform_conv_1_fu_257->input_V3_ce1(grp_dut_perform_conv_1_fu_257_input_V3_ce1);
    grp_dut_perform_conv_1_fu_257->input_V3_q1(mem_conv2_3_V_q1);
    grp_dut_perform_conv_1_fu_257->input_V4_address0(grp_dut_perform_conv_1_fu_257_input_V4_address0);
    grp_dut_perform_conv_1_fu_257->input_V4_ce0(grp_dut_perform_conv_1_fu_257_input_V4_ce0);
    grp_dut_perform_conv_1_fu_257->input_V4_q0(mem_conv2_4_V_q0);
    grp_dut_perform_conv_1_fu_257->input_V4_address1(grp_dut_perform_conv_1_fu_257_input_V4_address1);
    grp_dut_perform_conv_1_fu_257->input_V4_ce1(grp_dut_perform_conv_1_fu_257_input_V4_ce1);
    grp_dut_perform_conv_1_fu_257->input_V4_q1(mem_conv2_4_V_q1);
    grp_dut_perform_conv_1_fu_257->output_V_address0(grp_dut_perform_conv_1_fu_257_output_V_address0);
    grp_dut_perform_conv_1_fu_257->output_V_ce0(grp_dut_perform_conv_1_fu_257_output_V_ce0);
    grp_dut_perform_conv_1_fu_257->output_V_we0(grp_dut_perform_conv_1_fu_257_output_V_we0);
    grp_dut_perform_conv_1_fu_257->output_V_d0(grp_dut_perform_conv_1_fu_257_output_V_d0);
    grp_dut_perform_conv_1_fu_257->output_V_q0(mem_conv1_0_V_q0);
    grp_dut_perform_conv_1_fu_257->output_V5_address0(grp_dut_perform_conv_1_fu_257_output_V5_address0);
    grp_dut_perform_conv_1_fu_257->output_V5_ce0(grp_dut_perform_conv_1_fu_257_output_V5_ce0);
    grp_dut_perform_conv_1_fu_257->output_V5_we0(grp_dut_perform_conv_1_fu_257_output_V5_we0);
    grp_dut_perform_conv_1_fu_257->output_V5_d0(grp_dut_perform_conv_1_fu_257_output_V5_d0);
    grp_dut_perform_conv_1_fu_257->output_V5_q0(mem_conv1_1_V_q0);
    grp_dut_perform_conv_1_fu_257->output_V6_address0(grp_dut_perform_conv_1_fu_257_output_V6_address0);
    grp_dut_perform_conv_1_fu_257->output_V6_ce0(grp_dut_perform_conv_1_fu_257_output_V6_ce0);
    grp_dut_perform_conv_1_fu_257->output_V6_we0(grp_dut_perform_conv_1_fu_257_output_V6_we0);
    grp_dut_perform_conv_1_fu_257->output_V6_d0(grp_dut_perform_conv_1_fu_257_output_V6_d0);
    grp_dut_perform_conv_1_fu_257->output_V6_q0(mem_conv1_2_V_q0);
    grp_dut_perform_conv_fu_273 = new dut_perform_conv("grp_dut_perform_conv_fu_273");
    grp_dut_perform_conv_fu_273->ap_clk(ap_clk);
    grp_dut_perform_conv_fu_273->ap_rst(ap_rst);
    grp_dut_perform_conv_fu_273->ap_start(grp_dut_perform_conv_fu_273_ap_start);
    grp_dut_perform_conv_fu_273->ap_done(grp_dut_perform_conv_fu_273_ap_done);
    grp_dut_perform_conv_fu_273->ap_idle(grp_dut_perform_conv_fu_273_ap_idle);
    grp_dut_perform_conv_fu_273->ap_ready(grp_dut_perform_conv_fu_273_ap_ready);
    grp_dut_perform_conv_fu_273->input_0_V_address0(grp_dut_perform_conv_fu_273_input_0_V_address0);
    grp_dut_perform_conv_fu_273->input_0_V_ce0(grp_dut_perform_conv_fu_273_input_0_V_ce0);
    grp_dut_perform_conv_fu_273->input_0_V_q0(mem_conv1_0_V_q0);
    grp_dut_perform_conv_fu_273->input_0_V_address1(grp_dut_perform_conv_fu_273_input_0_V_address1);
    grp_dut_perform_conv_fu_273->input_0_V_ce1(grp_dut_perform_conv_fu_273_input_0_V_ce1);
    grp_dut_perform_conv_fu_273->input_0_V_q1(mem_conv1_0_V_q1);
    grp_dut_perform_conv_fu_273->input_1_V_address0(grp_dut_perform_conv_fu_273_input_1_V_address0);
    grp_dut_perform_conv_fu_273->input_1_V_ce0(grp_dut_perform_conv_fu_273_input_1_V_ce0);
    grp_dut_perform_conv_fu_273->input_1_V_q0(mem_conv1_1_V_q0);
    grp_dut_perform_conv_fu_273->input_1_V_address1(grp_dut_perform_conv_fu_273_input_1_V_address1);
    grp_dut_perform_conv_fu_273->input_1_V_ce1(grp_dut_perform_conv_fu_273_input_1_V_ce1);
    grp_dut_perform_conv_fu_273->input_1_V_q1(mem_conv1_1_V_q1);
    grp_dut_perform_conv_fu_273->input_2_V_address0(grp_dut_perform_conv_fu_273_input_2_V_address0);
    grp_dut_perform_conv_fu_273->input_2_V_ce0(grp_dut_perform_conv_fu_273_input_2_V_ce0);
    grp_dut_perform_conv_fu_273->input_2_V_q0(mem_conv1_2_V_q0);
    grp_dut_perform_conv_fu_273->input_2_V_address1(grp_dut_perform_conv_fu_273_input_2_V_address1);
    grp_dut_perform_conv_fu_273->input_2_V_ce1(grp_dut_perform_conv_fu_273_input_2_V_ce1);
    grp_dut_perform_conv_fu_273->input_2_V_q1(mem_conv1_2_V_q1);
    grp_dut_perform_conv_fu_273->output_0_V_address0(grp_dut_perform_conv_fu_273_output_0_V_address0);
    grp_dut_perform_conv_fu_273->output_0_V_ce0(grp_dut_perform_conv_fu_273_output_0_V_ce0);
    grp_dut_perform_conv_fu_273->output_0_V_we0(grp_dut_perform_conv_fu_273_output_0_V_we0);
    grp_dut_perform_conv_fu_273->output_0_V_d0(grp_dut_perform_conv_fu_273_output_0_V_d0);
    grp_dut_perform_conv_fu_273->output_0_V_q0(mem_conv2_0_V_q0);
    grp_dut_perform_conv_fu_273->output_1_V_address0(grp_dut_perform_conv_fu_273_output_1_V_address0);
    grp_dut_perform_conv_fu_273->output_1_V_ce0(grp_dut_perform_conv_fu_273_output_1_V_ce0);
    grp_dut_perform_conv_fu_273->output_1_V_we0(grp_dut_perform_conv_fu_273_output_1_V_we0);
    grp_dut_perform_conv_fu_273->output_1_V_d0(grp_dut_perform_conv_fu_273_output_1_V_d0);
    grp_dut_perform_conv_fu_273->output_1_V_q0(mem_conv2_1_V_q0);
    grp_dut_perform_conv_fu_273->output_2_V_address0(grp_dut_perform_conv_fu_273_output_2_V_address0);
    grp_dut_perform_conv_fu_273->output_2_V_ce0(grp_dut_perform_conv_fu_273_output_2_V_ce0);
    grp_dut_perform_conv_fu_273->output_2_V_we0(grp_dut_perform_conv_fu_273_output_2_V_we0);
    grp_dut_perform_conv_fu_273->output_2_V_d0(grp_dut_perform_conv_fu_273_output_2_V_d0);
    grp_dut_perform_conv_fu_273->output_2_V_q0(mem_conv2_2_V_q0);
    grp_dut_perform_conv_fu_273->output_3_V_address0(grp_dut_perform_conv_fu_273_output_3_V_address0);
    grp_dut_perform_conv_fu_273->output_3_V_ce0(grp_dut_perform_conv_fu_273_output_3_V_ce0);
    grp_dut_perform_conv_fu_273->output_3_V_we0(grp_dut_perform_conv_fu_273_output_3_V_we0);
    grp_dut_perform_conv_fu_273->output_3_V_d0(grp_dut_perform_conv_fu_273_output_3_V_d0);
    grp_dut_perform_conv_fu_273->output_3_V_q0(mem_conv2_3_V_q0);
    grp_dut_perform_conv_fu_273->output_4_V_address0(grp_dut_perform_conv_fu_273_output_4_V_address0);
    grp_dut_perform_conv_fu_273->output_4_V_ce0(grp_dut_perform_conv_fu_273_output_4_V_ce0);
    grp_dut_perform_conv_fu_273->output_4_V_we0(grp_dut_perform_conv_fu_273_output_4_V_we0);
    grp_dut_perform_conv_fu_273->output_4_V_d0(grp_dut_perform_conv_fu_273_output_4_V_d0);
    grp_dut_perform_conv_fu_273->output_4_V_q0(mem_conv2_4_V_q0);
    dut_sitofp_32s_32_6_U94 = new dut_sitofp_32s_32_6<1,6,32,32>("dut_sitofp_32s_32_6_U94");
    dut_sitofp_32s_32_6_U94->clk(ap_clk);
    dut_sitofp_32s_32_6_U94->reset(ap_rst);
    dut_sitofp_32s_32_6_U94->din0(grp_fu_289_p0);
    dut_sitofp_32s_32_6_U94->ce(ap_var_for_const0);
    dut_sitofp_32s_32_6_U94->dout(grp_fu_289_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( exitcond_fu_377_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( exitcond_fu_377_p2 );

    SC_METHOD(thread_ap_sig_110);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_121);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_31);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_339);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_349);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_363);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_397);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_56);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_73);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_99);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st13_fsm_12);
    sensitive << ( ap_sig_121 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_349 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_31 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_56 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_397 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_363 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_339 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_73 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_99 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_110 );

    SC_METHOD(thread_exitcond5_fu_296_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( bvh_d_index_reg_190 );

    SC_METHOD(thread_exitcond_fu_377_p2);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( i2_reg_223 );

    SC_METHOD(thread_exp_V_2_fu_486_p2);
    sensitive << ( exp_V_fu_476_p4 );

    SC_METHOD(thread_exp_V_fu_476_p4);
    sensitive << ( res_V_1_fu_472_p1 );

    SC_METHOD(thread_grp_dut_perform_conv_1_fu_257_ap_start);
    sensitive << ( ap_reg_grp_dut_perform_conv_1_fu_257_ap_start );

    SC_METHOD(thread_grp_dut_perform_conv_fu_273_ap_start);
    sensitive << ( ap_reg_grp_dut_perform_conv_fu_273_ap_start );

    SC_METHOD(thread_grp_fu_289_p0);
    sensitive << ( mem_conv1_V_load_phi_reg_585 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_i_3_fu_383_p2);
    sensitive << ( i2_reg_223 );

    SC_METHOD(thread_i_fu_302_p2);
    sensitive << ( bvh_d_index_reg_190 );

    SC_METHOD(thread_idx_urem8_fu_401_p3);
    sensitive << ( next_urem7_fu_389_p2 );
    sensitive << ( tmp_72_fu_395_p2 );

    SC_METHOD(thread_idx_urem_fu_369_p3);
    sensitive << ( next_urem_fu_357_p2 );
    sensitive << ( tmp_75_fu_363_p2 );

    SC_METHOD(thread_index_assign_cast6_fu_292_p1);
    sensitive << ( bvh_d_index_reg_190 );

    SC_METHOD(thread_mem_conv1_0_V_address0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond5_fu_296_p2 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( grp_dut_perform_conv_1_fu_257_output_V_address0 );
    sensitive << ( grp_dut_perform_conv_fu_273_input_0_V_address0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( newIndex_fu_350_p1 );
    sensitive << ( newIndex3_fu_429_p1 );
    sensitive << ( tmp_70_fu_330_p1 );

    SC_METHOD(thread_mem_conv1_0_V_ce0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond5_fu_296_p2 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( grp_dut_perform_conv_1_fu_257_output_V_ce0 );
    sensitive << ( grp_dut_perform_conv_fu_273_input_0_V_ce0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_70_fu_330_p1 );

    SC_METHOD(thread_mem_conv1_0_V_ce1);
    sensitive << ( grp_dut_perform_conv_fu_273_input_0_V_ce1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_mem_conv1_0_V_d0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond5_fu_296_p2 );
    sensitive << ( grp_dut_perform_conv_1_fu_257_output_V_d0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_70_fu_330_p1 );
    sensitive << ( tmp_22_cast_fu_323_p1 );

    SC_METHOD(thread_mem_conv1_0_V_we0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond5_fu_296_p2 );
    sensitive << ( grp_dut_perform_conv_1_fu_257_output_V_we0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_70_fu_330_p1 );

    SC_METHOD(thread_mem_conv1_1_V_address0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond5_fu_296_p2 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( grp_dut_perform_conv_1_fu_257_output_V5_address0 );
    sensitive << ( grp_dut_perform_conv_fu_273_input_1_V_address0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( newIndex_fu_350_p1 );
    sensitive << ( newIndex3_fu_429_p1 );
    sensitive << ( tmp_70_fu_330_p1 );

    SC_METHOD(thread_mem_conv1_1_V_ce0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond5_fu_296_p2 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( grp_dut_perform_conv_1_fu_257_output_V5_ce0 );
    sensitive << ( grp_dut_perform_conv_fu_273_input_1_V_ce0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_70_fu_330_p1 );

    SC_METHOD(thread_mem_conv1_1_V_ce1);
    sensitive << ( grp_dut_perform_conv_fu_273_input_1_V_ce1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_mem_conv1_1_V_d0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond5_fu_296_p2 );
    sensitive << ( grp_dut_perform_conv_1_fu_257_output_V5_d0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_70_fu_330_p1 );
    sensitive << ( tmp_22_cast_fu_323_p1 );

    SC_METHOD(thread_mem_conv1_1_V_we0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond5_fu_296_p2 );
    sensitive << ( grp_dut_perform_conv_1_fu_257_output_V5_we0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_70_fu_330_p1 );

    SC_METHOD(thread_mem_conv1_2_V_address0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond5_fu_296_p2 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( grp_dut_perform_conv_1_fu_257_output_V6_address0 );
    sensitive << ( grp_dut_perform_conv_fu_273_input_2_V_address0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( newIndex_fu_350_p1 );
    sensitive << ( newIndex3_fu_429_p1 );
    sensitive << ( tmp_70_fu_330_p1 );

    SC_METHOD(thread_mem_conv1_2_V_ce0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond5_fu_296_p2 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( grp_dut_perform_conv_1_fu_257_output_V6_ce0 );
    sensitive << ( grp_dut_perform_conv_fu_273_input_2_V_ce0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_70_fu_330_p1 );

    SC_METHOD(thread_mem_conv1_2_V_ce1);
    sensitive << ( grp_dut_perform_conv_fu_273_input_2_V_ce1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_mem_conv1_2_V_d0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond5_fu_296_p2 );
    sensitive << ( grp_dut_perform_conv_1_fu_257_output_V6_d0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_70_fu_330_p1 );
    sensitive << ( tmp_22_cast_fu_323_p1 );

    SC_METHOD(thread_mem_conv1_2_V_we0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond5_fu_296_p2 );
    sensitive << ( grp_dut_perform_conv_1_fu_257_output_V6_we0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_70_fu_330_p1 );

    SC_METHOD(thread_mem_conv1_V_load_phi_fu_455_p3);
    sensitive << ( sel_tmp2_reg_580 );
    sensitive << ( mem_conv1_1_V_q0 );
    sensitive << ( sel_tmp1_fu_448_p3 );

    SC_METHOD(thread_mem_conv2_0_V_address0);
    sensitive << ( grp_dut_perform_conv_1_fu_257_input_V_address0 );
    sensitive << ( grp_dut_perform_conv_fu_273_output_0_V_address0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_mem_conv2_0_V_ce0);
    sensitive << ( grp_dut_perform_conv_1_fu_257_input_V_ce0 );
    sensitive << ( grp_dut_perform_conv_fu_273_output_0_V_ce0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_mem_conv2_0_V_ce1);
    sensitive << ( grp_dut_perform_conv_1_fu_257_input_V_ce1 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_mem_conv2_1_V_address0);
    sensitive << ( grp_dut_perform_conv_1_fu_257_input_V1_address0 );
    sensitive << ( grp_dut_perform_conv_fu_273_output_1_V_address0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_mem_conv2_1_V_ce0);
    sensitive << ( grp_dut_perform_conv_1_fu_257_input_V1_ce0 );
    sensitive << ( grp_dut_perform_conv_fu_273_output_1_V_ce0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_mem_conv2_1_V_ce1);
    sensitive << ( grp_dut_perform_conv_1_fu_257_input_V1_ce1 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_mem_conv2_2_V_address0);
    sensitive << ( grp_dut_perform_conv_1_fu_257_input_V2_address0 );
    sensitive << ( grp_dut_perform_conv_fu_273_output_2_V_address0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_mem_conv2_2_V_ce0);
    sensitive << ( grp_dut_perform_conv_1_fu_257_input_V2_ce0 );
    sensitive << ( grp_dut_perform_conv_fu_273_output_2_V_ce0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_mem_conv2_2_V_ce1);
    sensitive << ( grp_dut_perform_conv_1_fu_257_input_V2_ce1 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_mem_conv2_3_V_address0);
    sensitive << ( grp_dut_perform_conv_1_fu_257_input_V3_address0 );
    sensitive << ( grp_dut_perform_conv_fu_273_output_3_V_address0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_mem_conv2_3_V_ce0);
    sensitive << ( grp_dut_perform_conv_1_fu_257_input_V3_ce0 );
    sensitive << ( grp_dut_perform_conv_fu_273_output_3_V_ce0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_mem_conv2_3_V_ce1);
    sensitive << ( grp_dut_perform_conv_1_fu_257_input_V3_ce1 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_mem_conv2_4_V_address0);
    sensitive << ( grp_dut_perform_conv_1_fu_257_input_V4_address0 );
    sensitive << ( grp_dut_perform_conv_fu_273_output_4_V_address0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_mem_conv2_4_V_ce0);
    sensitive << ( grp_dut_perform_conv_1_fu_257_input_V4_ce0 );
    sensitive << ( grp_dut_perform_conv_fu_273_output_4_V_ce0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_mem_conv2_4_V_ce1);
    sensitive << ( grp_dut_perform_conv_1_fu_257_input_V4_ce1 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_newIndex3_fu_429_p1);
    sensitive << ( tmp_74_fu_419_p4 );

    SC_METHOD(thread_newIndex_fu_350_p1);
    sensitive << ( tmp_71_fu_340_p4 );

    SC_METHOD(thread_next_mul5_fu_413_p2);
    sensitive << ( phi_mul4_reg_235 );

    SC_METHOD(thread_next_mul_fu_334_p2);
    sensitive << ( phi_mul_reg_201 );

    SC_METHOD(thread_next_urem7_fu_389_p2);
    sensitive << ( phi_urem6_reg_246 );

    SC_METHOD(thread_next_urem_fu_357_p2);
    sensitive << ( phi_urem_reg_212 );

    SC_METHOD(thread_output_V_address0);
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( tmp_16_fu_504_p1 );

    SC_METHOD(thread_output_V_ce0);
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_output_V_d0);
    sensitive << ( tmp_17_reg_590 );
    sensitive << ( p_Result_s_reg_600 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_output_V_we0);
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_p_Result_s_fu_492_p5);
    sensitive << ( res_V_1_fu_472_p1 );
    sensitive << ( exp_V_2_fu_486_p2 );

    SC_METHOD(thread_res_V_1_fu_472_p1);
    sensitive << ( grp_fu_289_p1 );

    SC_METHOD(thread_sel_tmp1_fu_448_p3);
    sensitive << ( sel_tmp_reg_575 );
    sensitive << ( mem_conv1_0_V_q0 );
    sensitive << ( mem_conv1_2_V_q0 );

    SC_METHOD(thread_sel_tmp2_fu_442_p2);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( exitcond_fu_377_p2 );
    sensitive << ( tmp_73_fu_409_p1 );

    SC_METHOD(thread_sel_tmp_fu_436_p2);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( exitcond_fu_377_p2 );
    sensitive << ( tmp_73_fu_409_p1 );

    SC_METHOD(thread_tmp_16_fu_504_p1);
    sensitive << ( i2_reg_223 );

    SC_METHOD(thread_tmp_17_fu_462_p2);
    sensitive << ( mem_conv1_V_load_phi_fu_455_p3 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_tmp_22_cast_fu_323_p1);
    sensitive << ( tmp_s_fu_315_p3 );

    SC_METHOD(thread_tmp_70_fu_330_p1);
    sensitive << ( phi_urem_reg_212 );

    SC_METHOD(thread_tmp_71_fu_340_p4);
    sensitive << ( phi_mul_reg_201 );

    SC_METHOD(thread_tmp_72_fu_395_p2);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( exitcond_fu_377_p2 );
    sensitive << ( next_urem7_fu_389_p2 );

    SC_METHOD(thread_tmp_73_fu_409_p1);
    sensitive << ( phi_urem6_reg_246 );

    SC_METHOD(thread_tmp_74_fu_419_p4);
    sensitive << ( phi_mul4_reg_235 );

    SC_METHOD(thread_tmp_75_fu_363_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond5_fu_296_p2 );
    sensitive << ( next_urem_fu_357_p2 );

    SC_METHOD(thread_tmp_fu_308_p3);
    sensitive << ( input_V );
    sensitive << ( index_assign_cast6_fu_292_p1 );

    SC_METHOD(thread_tmp_s_fu_315_p3);
    sensitive << ( tmp_fu_308_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond5_fu_296_p2 );
    sensitive << ( exitcond_fu_377_p2 );
    sensitive << ( grp_dut_perform_conv_1_fu_257_ap_done );
    sensitive << ( grp_dut_perform_conv_fu_273_ap_done );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000000000001";
    ap_reg_grp_dut_perform_conv_1_fu_257_ap_start = SC_LOGIC_0;
    ap_reg_grp_dut_perform_conv_fu_273_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dut_cnn_xcel_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_V, "(port)input_V");
    sc_trace(mVcdFile, output_V_address0, "(port)output_V_address0");
    sc_trace(mVcdFile, output_V_ce0, "(port)output_V_ce0");
    sc_trace(mVcdFile, output_V_we0, "(port)output_V_we0");
    sc_trace(mVcdFile, output_V_d0, "(port)output_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_31, "ap_sig_31");
    sc_trace(mVcdFile, i_fu_302_p2, "i_fu_302_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_56, "ap_sig_56");
    sc_trace(mVcdFile, next_mul_fu_334_p2, "next_mul_fu_334_p2");
    sc_trace(mVcdFile, exitcond5_fu_296_p2, "exitcond5_fu_296_p2");
    sc_trace(mVcdFile, idx_urem_fu_369_p3, "idx_urem_fu_369_p3");
    sc_trace(mVcdFile, i_3_fu_383_p2, "i_3_fu_383_p2");
    sc_trace(mVcdFile, i_3_reg_545, "i_3_reg_545");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_73, "ap_sig_73");
    sc_trace(mVcdFile, idx_urem8_fu_401_p3, "idx_urem8_fu_401_p3");
    sc_trace(mVcdFile, idx_urem8_reg_550, "idx_urem8_reg_550");
    sc_trace(mVcdFile, exitcond_fu_377_p2, "exitcond_fu_377_p2");
    sc_trace(mVcdFile, next_mul5_fu_413_p2, "next_mul5_fu_413_p2");
    sc_trace(mVcdFile, next_mul5_reg_555, "next_mul5_reg_555");
    sc_trace(mVcdFile, sel_tmp_fu_436_p2, "sel_tmp_fu_436_p2");
    sc_trace(mVcdFile, sel_tmp_reg_575, "sel_tmp_reg_575");
    sc_trace(mVcdFile, sel_tmp2_fu_442_p2, "sel_tmp2_fu_442_p2");
    sc_trace(mVcdFile, sel_tmp2_reg_580, "sel_tmp2_reg_580");
    sc_trace(mVcdFile, mem_conv1_V_load_phi_fu_455_p3, "mem_conv1_V_load_phi_fu_455_p3");
    sc_trace(mVcdFile, mem_conv1_V_load_phi_reg_585, "mem_conv1_V_load_phi_reg_585");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_99, "ap_sig_99");
    sc_trace(mVcdFile, tmp_17_fu_462_p2, "tmp_17_fu_462_p2");
    sc_trace(mVcdFile, tmp_17_reg_590, "tmp_17_reg_590");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_110, "ap_sig_110");
    sc_trace(mVcdFile, p_Result_s_fu_492_p5, "p_Result_s_fu_492_p5");
    sc_trace(mVcdFile, p_Result_s_reg_600, "p_Result_s_reg_600");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st13_fsm_12, "ap_sig_cseq_ST_st13_fsm_12");
    sc_trace(mVcdFile, ap_sig_121, "ap_sig_121");
    sc_trace(mVcdFile, mem_conv1_0_V_address0, "mem_conv1_0_V_address0");
    sc_trace(mVcdFile, mem_conv1_0_V_ce0, "mem_conv1_0_V_ce0");
    sc_trace(mVcdFile, mem_conv1_0_V_we0, "mem_conv1_0_V_we0");
    sc_trace(mVcdFile, mem_conv1_0_V_d0, "mem_conv1_0_V_d0");
    sc_trace(mVcdFile, mem_conv1_0_V_q0, "mem_conv1_0_V_q0");
    sc_trace(mVcdFile, mem_conv1_0_V_ce1, "mem_conv1_0_V_ce1");
    sc_trace(mVcdFile, mem_conv1_0_V_q1, "mem_conv1_0_V_q1");
    sc_trace(mVcdFile, mem_conv1_1_V_address0, "mem_conv1_1_V_address0");
    sc_trace(mVcdFile, mem_conv1_1_V_ce0, "mem_conv1_1_V_ce0");
    sc_trace(mVcdFile, mem_conv1_1_V_we0, "mem_conv1_1_V_we0");
    sc_trace(mVcdFile, mem_conv1_1_V_d0, "mem_conv1_1_V_d0");
    sc_trace(mVcdFile, mem_conv1_1_V_q0, "mem_conv1_1_V_q0");
    sc_trace(mVcdFile, mem_conv1_1_V_ce1, "mem_conv1_1_V_ce1");
    sc_trace(mVcdFile, mem_conv1_1_V_q1, "mem_conv1_1_V_q1");
    sc_trace(mVcdFile, mem_conv1_2_V_address0, "mem_conv1_2_V_address0");
    sc_trace(mVcdFile, mem_conv1_2_V_ce0, "mem_conv1_2_V_ce0");
    sc_trace(mVcdFile, mem_conv1_2_V_we0, "mem_conv1_2_V_we0");
    sc_trace(mVcdFile, mem_conv1_2_V_d0, "mem_conv1_2_V_d0");
    sc_trace(mVcdFile, mem_conv1_2_V_q0, "mem_conv1_2_V_q0");
    sc_trace(mVcdFile, mem_conv1_2_V_ce1, "mem_conv1_2_V_ce1");
    sc_trace(mVcdFile, mem_conv1_2_V_q1, "mem_conv1_2_V_q1");
    sc_trace(mVcdFile, mem_conv2_0_V_address0, "mem_conv2_0_V_address0");
    sc_trace(mVcdFile, mem_conv2_0_V_ce0, "mem_conv2_0_V_ce0");
    sc_trace(mVcdFile, mem_conv2_0_V_q0, "mem_conv2_0_V_q0");
    sc_trace(mVcdFile, mem_conv2_0_V_ce1, "mem_conv2_0_V_ce1");
    sc_trace(mVcdFile, mem_conv2_0_V_q1, "mem_conv2_0_V_q1");
    sc_trace(mVcdFile, mem_conv2_1_V_address0, "mem_conv2_1_V_address0");
    sc_trace(mVcdFile, mem_conv2_1_V_ce0, "mem_conv2_1_V_ce0");
    sc_trace(mVcdFile, mem_conv2_1_V_q0, "mem_conv2_1_V_q0");
    sc_trace(mVcdFile, mem_conv2_1_V_ce1, "mem_conv2_1_V_ce1");
    sc_trace(mVcdFile, mem_conv2_1_V_q1, "mem_conv2_1_V_q1");
    sc_trace(mVcdFile, mem_conv2_2_V_address0, "mem_conv2_2_V_address0");
    sc_trace(mVcdFile, mem_conv2_2_V_ce0, "mem_conv2_2_V_ce0");
    sc_trace(mVcdFile, mem_conv2_2_V_q0, "mem_conv2_2_V_q0");
    sc_trace(mVcdFile, mem_conv2_2_V_ce1, "mem_conv2_2_V_ce1");
    sc_trace(mVcdFile, mem_conv2_2_V_q1, "mem_conv2_2_V_q1");
    sc_trace(mVcdFile, mem_conv2_3_V_address0, "mem_conv2_3_V_address0");
    sc_trace(mVcdFile, mem_conv2_3_V_ce0, "mem_conv2_3_V_ce0");
    sc_trace(mVcdFile, mem_conv2_3_V_q0, "mem_conv2_3_V_q0");
    sc_trace(mVcdFile, mem_conv2_3_V_ce1, "mem_conv2_3_V_ce1");
    sc_trace(mVcdFile, mem_conv2_3_V_q1, "mem_conv2_3_V_q1");
    sc_trace(mVcdFile, mem_conv2_4_V_address0, "mem_conv2_4_V_address0");
    sc_trace(mVcdFile, mem_conv2_4_V_ce0, "mem_conv2_4_V_ce0");
    sc_trace(mVcdFile, mem_conv2_4_V_q0, "mem_conv2_4_V_q0");
    sc_trace(mVcdFile, mem_conv2_4_V_ce1, "mem_conv2_4_V_ce1");
    sc_trace(mVcdFile, mem_conv2_4_V_q1, "mem_conv2_4_V_q1");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_ap_start, "grp_dut_perform_conv_1_fu_257_ap_start");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_ap_done, "grp_dut_perform_conv_1_fu_257_ap_done");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_ap_idle, "grp_dut_perform_conv_1_fu_257_ap_idle");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_ap_ready, "grp_dut_perform_conv_1_fu_257_ap_ready");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V_address0, "grp_dut_perform_conv_1_fu_257_input_V_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V_ce0, "grp_dut_perform_conv_1_fu_257_input_V_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V_address1, "grp_dut_perform_conv_1_fu_257_input_V_address1");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V_ce1, "grp_dut_perform_conv_1_fu_257_input_V_ce1");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V1_address0, "grp_dut_perform_conv_1_fu_257_input_V1_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V1_ce0, "grp_dut_perform_conv_1_fu_257_input_V1_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V1_address1, "grp_dut_perform_conv_1_fu_257_input_V1_address1");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V1_ce1, "grp_dut_perform_conv_1_fu_257_input_V1_ce1");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V2_address0, "grp_dut_perform_conv_1_fu_257_input_V2_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V2_ce0, "grp_dut_perform_conv_1_fu_257_input_V2_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V2_address1, "grp_dut_perform_conv_1_fu_257_input_V2_address1");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V2_ce1, "grp_dut_perform_conv_1_fu_257_input_V2_ce1");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V3_address0, "grp_dut_perform_conv_1_fu_257_input_V3_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V3_ce0, "grp_dut_perform_conv_1_fu_257_input_V3_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V3_address1, "grp_dut_perform_conv_1_fu_257_input_V3_address1");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V3_ce1, "grp_dut_perform_conv_1_fu_257_input_V3_ce1");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V4_address0, "grp_dut_perform_conv_1_fu_257_input_V4_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V4_ce0, "grp_dut_perform_conv_1_fu_257_input_V4_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V4_address1, "grp_dut_perform_conv_1_fu_257_input_V4_address1");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_input_V4_ce1, "grp_dut_perform_conv_1_fu_257_input_V4_ce1");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_output_V_address0, "grp_dut_perform_conv_1_fu_257_output_V_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_output_V_ce0, "grp_dut_perform_conv_1_fu_257_output_V_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_output_V_we0, "grp_dut_perform_conv_1_fu_257_output_V_we0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_output_V_d0, "grp_dut_perform_conv_1_fu_257_output_V_d0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_output_V5_address0, "grp_dut_perform_conv_1_fu_257_output_V5_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_output_V5_ce0, "grp_dut_perform_conv_1_fu_257_output_V5_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_output_V5_we0, "grp_dut_perform_conv_1_fu_257_output_V5_we0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_output_V5_d0, "grp_dut_perform_conv_1_fu_257_output_V5_d0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_output_V6_address0, "grp_dut_perform_conv_1_fu_257_output_V6_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_output_V6_ce0, "grp_dut_perform_conv_1_fu_257_output_V6_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_output_V6_we0, "grp_dut_perform_conv_1_fu_257_output_V6_we0");
    sc_trace(mVcdFile, grp_dut_perform_conv_1_fu_257_output_V6_d0, "grp_dut_perform_conv_1_fu_257_output_V6_d0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_ap_start, "grp_dut_perform_conv_fu_273_ap_start");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_ap_done, "grp_dut_perform_conv_fu_273_ap_done");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_ap_idle, "grp_dut_perform_conv_fu_273_ap_idle");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_ap_ready, "grp_dut_perform_conv_fu_273_ap_ready");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_input_0_V_address0, "grp_dut_perform_conv_fu_273_input_0_V_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_input_0_V_ce0, "grp_dut_perform_conv_fu_273_input_0_V_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_input_0_V_address1, "grp_dut_perform_conv_fu_273_input_0_V_address1");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_input_0_V_ce1, "grp_dut_perform_conv_fu_273_input_0_V_ce1");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_input_1_V_address0, "grp_dut_perform_conv_fu_273_input_1_V_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_input_1_V_ce0, "grp_dut_perform_conv_fu_273_input_1_V_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_input_1_V_address1, "grp_dut_perform_conv_fu_273_input_1_V_address1");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_input_1_V_ce1, "grp_dut_perform_conv_fu_273_input_1_V_ce1");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_input_2_V_address0, "grp_dut_perform_conv_fu_273_input_2_V_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_input_2_V_ce0, "grp_dut_perform_conv_fu_273_input_2_V_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_input_2_V_address1, "grp_dut_perform_conv_fu_273_input_2_V_address1");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_input_2_V_ce1, "grp_dut_perform_conv_fu_273_input_2_V_ce1");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_0_V_address0, "grp_dut_perform_conv_fu_273_output_0_V_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_0_V_ce0, "grp_dut_perform_conv_fu_273_output_0_V_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_0_V_we0, "grp_dut_perform_conv_fu_273_output_0_V_we0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_0_V_d0, "grp_dut_perform_conv_fu_273_output_0_V_d0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_1_V_address0, "grp_dut_perform_conv_fu_273_output_1_V_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_1_V_ce0, "grp_dut_perform_conv_fu_273_output_1_V_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_1_V_we0, "grp_dut_perform_conv_fu_273_output_1_V_we0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_1_V_d0, "grp_dut_perform_conv_fu_273_output_1_V_d0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_2_V_address0, "grp_dut_perform_conv_fu_273_output_2_V_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_2_V_ce0, "grp_dut_perform_conv_fu_273_output_2_V_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_2_V_we0, "grp_dut_perform_conv_fu_273_output_2_V_we0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_2_V_d0, "grp_dut_perform_conv_fu_273_output_2_V_d0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_3_V_address0, "grp_dut_perform_conv_fu_273_output_3_V_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_3_V_ce0, "grp_dut_perform_conv_fu_273_output_3_V_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_3_V_we0, "grp_dut_perform_conv_fu_273_output_3_V_we0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_3_V_d0, "grp_dut_perform_conv_fu_273_output_3_V_d0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_4_V_address0, "grp_dut_perform_conv_fu_273_output_4_V_address0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_4_V_ce0, "grp_dut_perform_conv_fu_273_output_4_V_ce0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_4_V_we0, "grp_dut_perform_conv_fu_273_output_4_V_we0");
    sc_trace(mVcdFile, grp_dut_perform_conv_fu_273_output_4_V_d0, "grp_dut_perform_conv_fu_273_output_4_V_d0");
    sc_trace(mVcdFile, bvh_d_index_reg_190, "bvh_d_index_reg_190");
    sc_trace(mVcdFile, phi_mul_reg_201, "phi_mul_reg_201");
    sc_trace(mVcdFile, phi_urem_reg_212, "phi_urem_reg_212");
    sc_trace(mVcdFile, i2_reg_223, "i2_reg_223");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_339, "ap_sig_339");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_349, "ap_sig_349");
    sc_trace(mVcdFile, phi_mul4_reg_235, "phi_mul4_reg_235");
    sc_trace(mVcdFile, phi_urem6_reg_246, "phi_urem6_reg_246");
    sc_trace(mVcdFile, ap_reg_grp_dut_perform_conv_1_fu_257_ap_start, "ap_reg_grp_dut_perform_conv_1_fu_257_ap_start");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_363, "ap_sig_363");
    sc_trace(mVcdFile, ap_reg_grp_dut_perform_conv_fu_273_ap_start, "ap_reg_grp_dut_perform_conv_fu_273_ap_start");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_397, "ap_sig_397");
    sc_trace(mVcdFile, newIndex_fu_350_p1, "newIndex_fu_350_p1");
    sc_trace(mVcdFile, newIndex3_fu_429_p1, "newIndex3_fu_429_p1");
    sc_trace(mVcdFile, tmp_16_fu_504_p1, "tmp_16_fu_504_p1");
    sc_trace(mVcdFile, tmp_70_fu_330_p1, "tmp_70_fu_330_p1");
    sc_trace(mVcdFile, tmp_22_cast_fu_323_p1, "tmp_22_cast_fu_323_p1");
    sc_trace(mVcdFile, grp_fu_289_p0, "grp_fu_289_p0");
    sc_trace(mVcdFile, index_assign_cast6_fu_292_p1, "index_assign_cast6_fu_292_p1");
    sc_trace(mVcdFile, tmp_fu_308_p3, "tmp_fu_308_p3");
    sc_trace(mVcdFile, tmp_s_fu_315_p3, "tmp_s_fu_315_p3");
    sc_trace(mVcdFile, tmp_71_fu_340_p4, "tmp_71_fu_340_p4");
    sc_trace(mVcdFile, next_urem_fu_357_p2, "next_urem_fu_357_p2");
    sc_trace(mVcdFile, tmp_75_fu_363_p2, "tmp_75_fu_363_p2");
    sc_trace(mVcdFile, next_urem7_fu_389_p2, "next_urem7_fu_389_p2");
    sc_trace(mVcdFile, tmp_72_fu_395_p2, "tmp_72_fu_395_p2");
    sc_trace(mVcdFile, tmp_74_fu_419_p4, "tmp_74_fu_419_p4");
    sc_trace(mVcdFile, tmp_73_fu_409_p1, "tmp_73_fu_409_p1");
    sc_trace(mVcdFile, sel_tmp1_fu_448_p3, "sel_tmp1_fu_448_p3");
    sc_trace(mVcdFile, grp_fu_289_p1, "grp_fu_289_p1");
    sc_trace(mVcdFile, res_V_1_fu_472_p1, "res_V_1_fu_472_p1");
    sc_trace(mVcdFile, exp_V_fu_476_p4, "exp_V_fu_476_p4");
    sc_trace(mVcdFile, exp_V_2_fu_486_p2, "exp_V_2_fu_486_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

dut_cnn_xcel::~dut_cnn_xcel() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete mem_conv1_0_V_U;
    delete mem_conv1_1_V_U;
    delete mem_conv1_2_V_U;
    delete mem_conv2_0_V_U;
    delete mem_conv2_1_V_U;
    delete mem_conv2_2_V_U;
    delete mem_conv2_3_V_U;
    delete mem_conv2_4_V_U;
    delete grp_dut_perform_conv_1_fu_257;
    delete grp_dut_perform_conv_fu_273;
    delete dut_sitofp_32s_32_6_U94;
}

void dut_cnn_xcel::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void dut_cnn_xcel::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_dut_perform_conv_1_fu_257_ap_start = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
            ap_reg_grp_dut_perform_conv_1_fu_257_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_dut_perform_conv_1_fu_257_ap_ready.read())) {
            ap_reg_grp_dut_perform_conv_1_fu_257_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_dut_perform_conv_fu_273_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
             !esl_seteq<1,1,1>(exitcond5_fu_296_p2.read(), ap_const_lv1_0))) {
            ap_reg_grp_dut_perform_conv_fu_273_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_dut_perform_conv_fu_273_ap_ready.read())) {
            ap_reg_grp_dut_perform_conv_fu_273_ap_start = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_296_p2.read(), ap_const_lv1_0))) {
        bvh_d_index_reg_190 = i_fu_302_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        bvh_d_index_reg_190 = ap_const_lv6_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        i2_reg_223 = i_3_reg_545.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
                !esl_seteq<1,1,1>(ap_const_logic_0, grp_dut_perform_conv_1_fu_257_ap_done.read()))) {
        i2_reg_223 = ap_const_lv10_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        phi_mul4_reg_235 = next_mul5_reg_555.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
                !esl_seteq<1,1,1>(ap_const_logic_0, grp_dut_perform_conv_1_fu_257_ap_done.read()))) {
        phi_mul4_reg_235 = ap_const_lv20_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_296_p2.read(), ap_const_lv1_0))) {
        phi_mul_reg_201 = next_mul_fu_334_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        phi_mul_reg_201 = ap_const_lv13_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        phi_urem6_reg_246 = idx_urem8_reg_550.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
                !esl_seteq<1,1,1>(ap_const_logic_0, grp_dut_perform_conv_1_fu_257_ap_done.read()))) {
        phi_urem6_reg_246 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_296_p2.read(), ap_const_lv1_0))) {
        phi_urem_reg_212 = idx_urem_fu_369_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        phi_urem_reg_212 = ap_const_lv6_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        i_3_reg_545 = i_3_fu_383_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_377_p2.read()))) {
        idx_urem8_reg_550 = idx_urem8_fu_401_p3.read();
        next_mul5_reg_555 = next_mul5_fu_413_p2.read();
        sel_tmp2_reg_580 = sel_tmp2_fu_442_p2.read();
        sel_tmp_reg_575 = sel_tmp_fu_436_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        mem_conv1_V_load_phi_reg_585 = mem_conv1_V_load_phi_fu_455_p3.read();
        tmp_17_reg_590 = tmp_17_fu_462_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_reg_590.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()))) {
        p_Result_s_reg_600 = p_Result_s_fu_492_p5.read();
    }
}

void dut_cnn_xcel::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_377_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_377_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_ap_sig_110() {
    ap_sig_110 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void dut_cnn_xcel::thread_ap_sig_121() {
    ap_sig_121 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(12, 12));
}

void dut_cnn_xcel::thread_ap_sig_31() {
    ap_sig_31 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void dut_cnn_xcel::thread_ap_sig_339() {
    ap_sig_339 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void dut_cnn_xcel::thread_ap_sig_349() {
    ap_sig_349 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void dut_cnn_xcel::thread_ap_sig_363() {
    ap_sig_363 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void dut_cnn_xcel::thread_ap_sig_397() {
    ap_sig_397 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void dut_cnn_xcel::thread_ap_sig_56() {
    ap_sig_56 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void dut_cnn_xcel::thread_ap_sig_73() {
    ap_sig_73 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void dut_cnn_xcel::thread_ap_sig_99() {
    ap_sig_99 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void dut_cnn_xcel::thread_ap_sig_cseq_ST_st13_fsm_12() {
    if (ap_sig_121.read()) {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_349.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_31.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_56.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_397.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_363.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_339.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_73.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_99.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_110.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_exitcond5_fu_296_p2() {
    exitcond5_fu_296_p2 = (!bvh_d_index_reg_190.read().is_01() || !ap_const_lv6_31.is_01())? sc_lv<1>(): sc_lv<1>(bvh_d_index_reg_190.read() == ap_const_lv6_31);
}

void dut_cnn_xcel::thread_exitcond_fu_377_p2() {
    exitcond_fu_377_p2 = (!i2_reg_223.read().is_01() || !ap_const_lv10_240.is_01())? sc_lv<1>(): sc_lv<1>(i2_reg_223.read() == ap_const_lv10_240);
}

void dut_cnn_xcel::thread_exp_V_2_fu_486_p2() {
    exp_V_2_fu_486_p2 = (!ap_const_lv8_F4.is_01() || !exp_V_fu_476_p4.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_F4) + sc_biguint<8>(exp_V_fu_476_p4.read()));
}

void dut_cnn_xcel::thread_exp_V_fu_476_p4() {
    exp_V_fu_476_p4 = res_V_1_fu_472_p1.read().range(30, 23);
}

void dut_cnn_xcel::thread_grp_dut_perform_conv_1_fu_257_ap_start() {
    grp_dut_perform_conv_1_fu_257_ap_start = ap_reg_grp_dut_perform_conv_1_fu_257_ap_start.read();
}

void dut_cnn_xcel::thread_grp_dut_perform_conv_fu_273_ap_start() {
    grp_dut_perform_conv_fu_273_ap_start = ap_reg_grp_dut_perform_conv_fu_273_ap_start.read();
}

void dut_cnn_xcel::thread_grp_fu_289_p0() {
    grp_fu_289_p0 = esl_sext<32,14>(mem_conv1_V_load_phi_reg_585.read());
}

void dut_cnn_xcel::thread_i_3_fu_383_p2() {
    i_3_fu_383_p2 = (!i2_reg_223.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(i2_reg_223.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void dut_cnn_xcel::thread_i_fu_302_p2() {
    i_fu_302_p2 = (!bvh_d_index_reg_190.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(bvh_d_index_reg_190.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void dut_cnn_xcel::thread_idx_urem8_fu_401_p3() {
    idx_urem8_fu_401_p3 = (!tmp_72_fu_395_p2.read()[0].is_01())? sc_lv<10>(): ((tmp_72_fu_395_p2.read()[0].to_bool())? next_urem7_fu_389_p2.read(): ap_const_lv10_0);
}

void dut_cnn_xcel::thread_idx_urem_fu_369_p3() {
    idx_urem_fu_369_p3 = (!tmp_75_fu_363_p2.read()[0].is_01())? sc_lv<6>(): ((tmp_75_fu_363_p2.read()[0].to_bool())? next_urem_fu_357_p2.read(): ap_const_lv6_0);
}

void dut_cnn_xcel::thread_index_assign_cast6_fu_292_p1() {
    index_assign_cast6_fu_292_p1 = esl_zext<32,6>(bvh_d_index_reg_190.read());
}

void dut_cnn_xcel::thread_mem_conv1_0_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_296_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,3,3>(tmp_70_fu_330_p1.read(), ap_const_lv3_0))) {
        mem_conv1_0_V_address0 =  (sc_lv<9>) (newIndex_fu_350_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        mem_conv1_0_V_address0 =  (sc_lv<9>) (newIndex3_fu_429_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv1_0_V_address0 = grp_dut_perform_conv_fu_273_input_0_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv1_0_V_address0 = grp_dut_perform_conv_1_fu_257_output_V_address0.read();
    } else {
        mem_conv1_0_V_address0 = "XXXXXXXXX";
    }
}

void dut_cnn_xcel::thread_mem_conv1_0_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(exitcond5_fu_296_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,3,3>(tmp_70_fu_330_p1.read(), ap_const_lv3_0)))) {
        mem_conv1_0_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv1_0_V_ce0 = grp_dut_perform_conv_fu_273_input_0_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv1_0_V_ce0 = grp_dut_perform_conv_1_fu_257_output_V_ce0.read();
    } else {
        mem_conv1_0_V_ce0 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_mem_conv1_0_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv1_0_V_ce1 = grp_dut_perform_conv_fu_273_input_0_V_ce1.read();
    } else {
        mem_conv1_0_V_ce1 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_mem_conv1_0_V_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_296_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,3,3>(tmp_70_fu_330_p1.read(), ap_const_lv3_0))) {
        mem_conv1_0_V_d0 = tmp_22_cast_fu_323_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv1_0_V_d0 = grp_dut_perform_conv_1_fu_257_output_V_d0.read();
    } else {
        mem_conv1_0_V_d0 =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
    }
}

void dut_cnn_xcel::thread_mem_conv1_0_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(exitcond5_fu_296_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,3,3>(tmp_70_fu_330_p1.read(), ap_const_lv3_0)))) {
        mem_conv1_0_V_we0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv1_0_V_we0 = grp_dut_perform_conv_1_fu_257_output_V_we0.read();
    } else {
        mem_conv1_0_V_we0 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_mem_conv1_1_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_296_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,3,3>(tmp_70_fu_330_p1.read(), ap_const_lv3_1))) {
        mem_conv1_1_V_address0 =  (sc_lv<9>) (newIndex_fu_350_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        mem_conv1_1_V_address0 =  (sc_lv<9>) (newIndex3_fu_429_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv1_1_V_address0 = grp_dut_perform_conv_fu_273_input_1_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv1_1_V_address0 = grp_dut_perform_conv_1_fu_257_output_V5_address0.read();
    } else {
        mem_conv1_1_V_address0 = "XXXXXXXXX";
    }
}

void dut_cnn_xcel::thread_mem_conv1_1_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(exitcond5_fu_296_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,3,3>(tmp_70_fu_330_p1.read(), ap_const_lv3_1)))) {
        mem_conv1_1_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv1_1_V_ce0 = grp_dut_perform_conv_fu_273_input_1_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv1_1_V_ce0 = grp_dut_perform_conv_1_fu_257_output_V5_ce0.read();
    } else {
        mem_conv1_1_V_ce0 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_mem_conv1_1_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv1_1_V_ce1 = grp_dut_perform_conv_fu_273_input_1_V_ce1.read();
    } else {
        mem_conv1_1_V_ce1 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_mem_conv1_1_V_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_296_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,3,3>(tmp_70_fu_330_p1.read(), ap_const_lv3_1))) {
        mem_conv1_1_V_d0 = tmp_22_cast_fu_323_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv1_1_V_d0 = grp_dut_perform_conv_1_fu_257_output_V5_d0.read();
    } else {
        mem_conv1_1_V_d0 =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
    }
}

void dut_cnn_xcel::thread_mem_conv1_1_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(exitcond5_fu_296_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,3,3>(tmp_70_fu_330_p1.read(), ap_const_lv3_1)))) {
        mem_conv1_1_V_we0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv1_1_V_we0 = grp_dut_perform_conv_1_fu_257_output_V5_we0.read();
    } else {
        mem_conv1_1_V_we0 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_mem_conv1_2_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_296_p2.read(), ap_const_lv1_0) && 
         !esl_seteq<1,3,3>(tmp_70_fu_330_p1.read(), ap_const_lv3_0) && 
         !esl_seteq<1,3,3>(tmp_70_fu_330_p1.read(), ap_const_lv3_1))) {
        mem_conv1_2_V_address0 =  (sc_lv<9>) (newIndex_fu_350_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        mem_conv1_2_V_address0 =  (sc_lv<9>) (newIndex3_fu_429_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv1_2_V_address0 = grp_dut_perform_conv_fu_273_input_2_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv1_2_V_address0 = grp_dut_perform_conv_1_fu_257_output_V6_address0.read();
    } else {
        mem_conv1_2_V_address0 = "XXXXXXXXX";
    }
}

void dut_cnn_xcel::thread_mem_conv1_2_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(exitcond5_fu_296_p2.read(), ap_const_lv1_0) && 
          !esl_seteq<1,3,3>(tmp_70_fu_330_p1.read(), ap_const_lv3_0) && 
          !esl_seteq<1,3,3>(tmp_70_fu_330_p1.read(), ap_const_lv3_1)))) {
        mem_conv1_2_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv1_2_V_ce0 = grp_dut_perform_conv_fu_273_input_2_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv1_2_V_ce0 = grp_dut_perform_conv_1_fu_257_output_V6_ce0.read();
    } else {
        mem_conv1_2_V_ce0 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_mem_conv1_2_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv1_2_V_ce1 = grp_dut_perform_conv_fu_273_input_2_V_ce1.read();
    } else {
        mem_conv1_2_V_ce1 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_mem_conv1_2_V_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_296_p2.read(), ap_const_lv1_0) && 
         !esl_seteq<1,3,3>(tmp_70_fu_330_p1.read(), ap_const_lv3_0) && 
         !esl_seteq<1,3,3>(tmp_70_fu_330_p1.read(), ap_const_lv3_1))) {
        mem_conv1_2_V_d0 = tmp_22_cast_fu_323_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv1_2_V_d0 = grp_dut_perform_conv_1_fu_257_output_V6_d0.read();
    } else {
        mem_conv1_2_V_d0 =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
    }
}

void dut_cnn_xcel::thread_mem_conv1_2_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(exitcond5_fu_296_p2.read(), ap_const_lv1_0) && 
          !esl_seteq<1,3,3>(tmp_70_fu_330_p1.read(), ap_const_lv3_0) && 
          !esl_seteq<1,3,3>(tmp_70_fu_330_p1.read(), ap_const_lv3_1)))) {
        mem_conv1_2_V_we0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv1_2_V_we0 = grp_dut_perform_conv_1_fu_257_output_V6_we0.read();
    } else {
        mem_conv1_2_V_we0 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_mem_conv1_V_load_phi_fu_455_p3() {
    mem_conv1_V_load_phi_fu_455_p3 = (!sel_tmp2_reg_580.read()[0].is_01())? sc_lv<14>(): ((sel_tmp2_reg_580.read()[0].to_bool())? mem_conv1_1_V_q0.read(): sel_tmp1_fu_448_p3.read());
}

void dut_cnn_xcel::thread_mem_conv2_0_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv2_0_V_address0 = grp_dut_perform_conv_fu_273_output_0_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv2_0_V_address0 = grp_dut_perform_conv_1_fu_257_input_V_address0.read();
    } else {
        mem_conv2_0_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void dut_cnn_xcel::thread_mem_conv2_0_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv2_0_V_ce0 = grp_dut_perform_conv_fu_273_output_0_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv2_0_V_ce0 = grp_dut_perform_conv_1_fu_257_input_V_ce0.read();
    } else {
        mem_conv2_0_V_ce0 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_mem_conv2_0_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv2_0_V_ce1 = grp_dut_perform_conv_1_fu_257_input_V_ce1.read();
    } else {
        mem_conv2_0_V_ce1 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_mem_conv2_1_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv2_1_V_address0 = grp_dut_perform_conv_fu_273_output_1_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv2_1_V_address0 = grp_dut_perform_conv_1_fu_257_input_V1_address0.read();
    } else {
        mem_conv2_1_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void dut_cnn_xcel::thread_mem_conv2_1_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv2_1_V_ce0 = grp_dut_perform_conv_fu_273_output_1_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv2_1_V_ce0 = grp_dut_perform_conv_1_fu_257_input_V1_ce0.read();
    } else {
        mem_conv2_1_V_ce0 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_mem_conv2_1_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv2_1_V_ce1 = grp_dut_perform_conv_1_fu_257_input_V1_ce1.read();
    } else {
        mem_conv2_1_V_ce1 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_mem_conv2_2_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv2_2_V_address0 = grp_dut_perform_conv_fu_273_output_2_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv2_2_V_address0 = grp_dut_perform_conv_1_fu_257_input_V2_address0.read();
    } else {
        mem_conv2_2_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void dut_cnn_xcel::thread_mem_conv2_2_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv2_2_V_ce0 = grp_dut_perform_conv_fu_273_output_2_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv2_2_V_ce0 = grp_dut_perform_conv_1_fu_257_input_V2_ce0.read();
    } else {
        mem_conv2_2_V_ce0 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_mem_conv2_2_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv2_2_V_ce1 = grp_dut_perform_conv_1_fu_257_input_V2_ce1.read();
    } else {
        mem_conv2_2_V_ce1 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_mem_conv2_3_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv2_3_V_address0 = grp_dut_perform_conv_fu_273_output_3_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv2_3_V_address0 = grp_dut_perform_conv_1_fu_257_input_V3_address0.read();
    } else {
        mem_conv2_3_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void dut_cnn_xcel::thread_mem_conv2_3_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv2_3_V_ce0 = grp_dut_perform_conv_fu_273_output_3_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv2_3_V_ce0 = grp_dut_perform_conv_1_fu_257_input_V3_ce0.read();
    } else {
        mem_conv2_3_V_ce0 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_mem_conv2_3_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv2_3_V_ce1 = grp_dut_perform_conv_1_fu_257_input_V3_ce1.read();
    } else {
        mem_conv2_3_V_ce1 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_mem_conv2_4_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv2_4_V_address0 = grp_dut_perform_conv_fu_273_output_4_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv2_4_V_address0 = grp_dut_perform_conv_1_fu_257_input_V4_address0.read();
    } else {
        mem_conv2_4_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void dut_cnn_xcel::thread_mem_conv2_4_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        mem_conv2_4_V_ce0 = grp_dut_perform_conv_fu_273_output_4_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv2_4_V_ce0 = grp_dut_perform_conv_1_fu_257_input_V4_ce0.read();
    } else {
        mem_conv2_4_V_ce0 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_mem_conv2_4_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        mem_conv2_4_V_ce1 = grp_dut_perform_conv_1_fu_257_input_V4_ce1.read();
    } else {
        mem_conv2_4_V_ce1 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_newIndex3_fu_429_p1() {
    newIndex3_fu_429_p1 = esl_zext<64,8>(tmp_74_fu_419_p4.read());
}

void dut_cnn_xcel::thread_newIndex_fu_350_p1() {
    newIndex_fu_350_p1 = esl_zext<64,5>(tmp_71_fu_340_p4.read());
}

void dut_cnn_xcel::thread_next_mul5_fu_413_p2() {
    next_mul5_fu_413_p2 = (!ap_const_lv20_556.is_01() || !phi_mul4_reg_235.read().is_01())? sc_lv<20>(): (sc_biguint<20>(ap_const_lv20_556) + sc_biguint<20>(phi_mul4_reg_235.read()));
}

void dut_cnn_xcel::thread_next_mul_fu_334_p2() {
    next_mul_fu_334_p2 = (!ap_const_lv13_56.is_01() || !phi_mul_reg_201.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_56) + sc_biguint<13>(phi_mul_reg_201.read()));
}

void dut_cnn_xcel::thread_next_urem7_fu_389_p2() {
    next_urem7_fu_389_p2 = (!ap_const_lv10_1.is_01() || !phi_urem6_reg_246.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_1) + sc_biguint<10>(phi_urem6_reg_246.read()));
}

void dut_cnn_xcel::thread_next_urem_fu_357_p2() {
    next_urem_fu_357_p2 = (!phi_urem_reg_212.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(phi_urem_reg_212.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void dut_cnn_xcel::thread_output_V_address0() {
    output_V_address0 =  (sc_lv<10>) (tmp_16_fu_504_p1.read());
}

void dut_cnn_xcel::thread_output_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        output_V_ce0 = ap_const_logic_1;
    } else {
        output_V_ce0 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_output_V_d0() {
    output_V_d0 = (!tmp_17_reg_590.read()[0].is_01())? sc_lv<32>(): ((tmp_17_reg_590.read()[0].to_bool())? ap_const_lv32_0: p_Result_s_reg_600.read());
}

void dut_cnn_xcel::thread_output_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        output_V_we0 = ap_const_logic_1;
    } else {
        output_V_we0 = ap_const_logic_0;
    }
}

void dut_cnn_xcel::thread_p_Result_s_fu_492_p5() {
    p_Result_s_fu_492_p5 = esl_partset<32,32,8,32,32>(res_V_1_fu_472_p1.read(), exp_V_2_fu_486_p2.read(), ap_const_lv32_17, ap_const_lv32_1E);
}

void dut_cnn_xcel::thread_res_V_1_fu_472_p1() {
    res_V_1_fu_472_p1 = grp_fu_289_p1.read();
}

void dut_cnn_xcel::thread_sel_tmp1_fu_448_p3() {
    sel_tmp1_fu_448_p3 = (!sel_tmp_reg_575.read()[0].is_01())? sc_lv<14>(): ((sel_tmp_reg_575.read()[0].to_bool())? mem_conv1_0_V_q0.read(): mem_conv1_2_V_q0.read());
}

void dut_cnn_xcel::thread_sel_tmp2_fu_442_p2() {
    sel_tmp2_fu_442_p2 = (!tmp_73_fu_409_p1.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_73_fu_409_p1.read() == ap_const_lv3_1);
}

void dut_cnn_xcel::thread_sel_tmp_fu_436_p2() {
    sel_tmp_fu_436_p2 = (!tmp_73_fu_409_p1.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_73_fu_409_p1.read() == ap_const_lv3_0);
}

void dut_cnn_xcel::thread_tmp_16_fu_504_p1() {
    tmp_16_fu_504_p1 = esl_zext<64,10>(i2_reg_223.read());
}

void dut_cnn_xcel::thread_tmp_17_fu_462_p2() {
    tmp_17_fu_462_p2 = (!mem_conv1_V_load_phi_fu_455_p3.read().is_01() || !ap_const_lv14_0.is_01())? sc_lv<1>(): sc_lv<1>(mem_conv1_V_load_phi_fu_455_p3.read() == ap_const_lv14_0);
}

void dut_cnn_xcel::thread_tmp_22_cast_fu_323_p1() {
    tmp_22_cast_fu_323_p1 = esl_zext<14,13>(tmp_s_fu_315_p3.read());
}

void dut_cnn_xcel::thread_tmp_70_fu_330_p1() {
    tmp_70_fu_330_p1 = phi_urem_reg_212.read().range(3-1, 0);
}

void dut_cnn_xcel::thread_tmp_71_fu_340_p4() {
    tmp_71_fu_340_p4 = phi_mul_reg_201.read().range(12, 8);
}

void dut_cnn_xcel::thread_tmp_72_fu_395_p2() {
    tmp_72_fu_395_p2 = (!next_urem7_fu_389_p2.read().is_01() || !ap_const_lv10_3.is_01())? sc_lv<1>(): (sc_biguint<10>(next_urem7_fu_389_p2.read()) < sc_biguint<10>(ap_const_lv10_3));
}

void dut_cnn_xcel::thread_tmp_73_fu_409_p1() {
    tmp_73_fu_409_p1 = phi_urem6_reg_246.read().range(3-1, 0);
}

void dut_cnn_xcel::thread_tmp_74_fu_419_p4() {
    tmp_74_fu_419_p4 = phi_mul4_reg_235.read().range(19, 12);
}

void dut_cnn_xcel::thread_tmp_75_fu_363_p2() {
    tmp_75_fu_363_p2 = (!next_urem_fu_357_p2.read().is_01() || !ap_const_lv6_3.is_01())? sc_lv<1>(): (sc_biguint<6>(next_urem_fu_357_p2.read()) < sc_biguint<6>(ap_const_lv6_3));
}

void dut_cnn_xcel::thread_tmp_fu_308_p3() {
    tmp_fu_308_p3 = (!index_assign_cast6_fu_292_p1.read().is_01() || sc_biguint<32>(index_assign_cast6_fu_292_p1.read()).to_uint() >= 49)? sc_lv<1>(): input_V.read().range(sc_biguint<32>(index_assign_cast6_fu_292_p1.read()).to_uint(), sc_biguint<32>(index_assign_cast6_fu_292_p1.read()).to_uint());
}

void dut_cnn_xcel::thread_tmp_s_fu_315_p3() {
    tmp_s_fu_315_p3 = esl_concat<1,12>(tmp_fu_308_p3.read(), ap_const_lv12_0);
}

void dut_cnn_xcel::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(exitcond5_fu_296_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_dut_perform_conv_fu_273_ap_done.read())) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_dut_perform_conv_1_fu_257_ap_done.read())) {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            }
            break;
        case 32 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_377_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
            break;
    }
}

}

