// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dut_cnn_xcel (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_V,
        output_V_address0,
        output_V_ce0,
        output_V_we0,
        output_V_d0
);

parameter    ap_ST_st1_fsm_0 = 14'b1;
parameter    ap_ST_st2_fsm_1 = 14'b10;
parameter    ap_ST_st3_fsm_2 = 14'b100;
parameter    ap_ST_st4_fsm_3 = 14'b1000;
parameter    ap_ST_st5_fsm_4 = 14'b10000;
parameter    ap_ST_st6_fsm_5 = 14'b100000;
parameter    ap_ST_st7_fsm_6 = 14'b1000000;
parameter    ap_ST_st8_fsm_7 = 14'b10000000;
parameter    ap_ST_st9_fsm_8 = 14'b100000000;
parameter    ap_ST_st10_fsm_9 = 14'b1000000000;
parameter    ap_ST_st11_fsm_10 = 14'b10000000000;
parameter    ap_ST_st12_fsm_11 = 14'b100000000000;
parameter    ap_ST_st13_fsm_12 = 14'b1000000000000;
parameter    ap_ST_st14_fsm_13 = 14'b10000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv13_0 = 13'b0000000000000;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv20_0 = 20'b00000000000000000000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv6_31 = 6'b110001;
parameter    ap_const_lv6_1 = 6'b1;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv13_56 = 13'b1010110;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv6_3 = 6'b11;
parameter    ap_const_lv10_240 = 10'b1001000000;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv10_3 = 10'b11;
parameter    ap_const_lv20_556 = 20'b10101010110;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv14_0 = 14'b00000000000000;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv8_F4 = 8'b11110100;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [48:0] input_V;
output  [9:0] output_V_address0;
output   output_V_ce0;
output   output_V_we0;
output  [31:0] output_V_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg output_V_ce0;
reg output_V_we0;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_31;
wire   [5:0] i_fu_302_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_56;
wire   [12:0] next_mul_fu_334_p2;
wire   [0:0] exitcond5_fu_296_p2;
wire   [5:0] idx_urem_fu_369_p3;
wire   [9:0] i_3_fu_383_p2;
reg   [9:0] i_3_reg_545;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_73;
wire   [9:0] idx_urem8_fu_401_p3;
reg   [9:0] idx_urem8_reg_550;
wire   [0:0] exitcond_fu_377_p2;
wire   [19:0] next_mul5_fu_413_p2;
reg   [19:0] next_mul5_reg_555;
wire   [0:0] sel_tmp_fu_436_p2;
reg   [0:0] sel_tmp_reg_575;
wire   [0:0] sel_tmp2_fu_442_p2;
reg   [0:0] sel_tmp2_reg_580;
wire   [13:0] mem_conv1_V_load_phi_fu_455_p3;
reg   [13:0] mem_conv1_V_load_phi_reg_585;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_99;
wire   [0:0] tmp_17_fu_462_p2;
reg   [0:0] tmp_17_reg_590;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_110;
wire   [31:0] p_Result_s_fu_492_p5;
reg   [31:0] p_Result_s_reg_600;
reg    ap_sig_cseq_ST_st13_fsm_12;
reg    ap_sig_121;
reg   [8:0] mem_conv1_0_V_address0;
reg    mem_conv1_0_V_ce0;
reg    mem_conv1_0_V_we0;
reg   [13:0] mem_conv1_0_V_d0;
wire   [13:0] mem_conv1_0_V_q0;
reg    mem_conv1_0_V_ce1;
wire   [13:0] mem_conv1_0_V_q1;
reg   [8:0] mem_conv1_1_V_address0;
reg    mem_conv1_1_V_ce0;
reg    mem_conv1_1_V_we0;
reg   [13:0] mem_conv1_1_V_d0;
wire   [13:0] mem_conv1_1_V_q0;
reg    mem_conv1_1_V_ce1;
wire   [13:0] mem_conv1_1_V_q1;
reg   [8:0] mem_conv1_2_V_address0;
reg    mem_conv1_2_V_ce0;
reg    mem_conv1_2_V_we0;
reg   [13:0] mem_conv1_2_V_d0;
wire   [13:0] mem_conv1_2_V_q0;
reg    mem_conv1_2_V_ce1;
wire   [13:0] mem_conv1_2_V_q1;
reg   [7:0] mem_conv2_0_V_address0;
reg    mem_conv2_0_V_ce0;
wire   [13:0] mem_conv2_0_V_q0;
reg    mem_conv2_0_V_ce1;
wire   [13:0] mem_conv2_0_V_q1;
reg   [7:0] mem_conv2_1_V_address0;
reg    mem_conv2_1_V_ce0;
wire   [13:0] mem_conv2_1_V_q0;
reg    mem_conv2_1_V_ce1;
wire   [13:0] mem_conv2_1_V_q1;
reg   [7:0] mem_conv2_2_V_address0;
reg    mem_conv2_2_V_ce0;
wire   [13:0] mem_conv2_2_V_q0;
reg    mem_conv2_2_V_ce1;
wire   [13:0] mem_conv2_2_V_q1;
reg   [7:0] mem_conv2_3_V_address0;
reg    mem_conv2_3_V_ce0;
wire   [13:0] mem_conv2_3_V_q0;
reg    mem_conv2_3_V_ce1;
wire   [13:0] mem_conv2_3_V_q1;
reg   [7:0] mem_conv2_4_V_address0;
reg    mem_conv2_4_V_ce0;
wire   [13:0] mem_conv2_4_V_q0;
reg    mem_conv2_4_V_ce1;
wire   [13:0] mem_conv2_4_V_q1;
wire    grp_dut_perform_conv_1_fu_257_ap_start;
wire    grp_dut_perform_conv_1_fu_257_ap_done;
wire    grp_dut_perform_conv_1_fu_257_ap_idle;
wire    grp_dut_perform_conv_1_fu_257_ap_ready;
wire   [7:0] grp_dut_perform_conv_1_fu_257_input_V_address0;
wire    grp_dut_perform_conv_1_fu_257_input_V_ce0;
wire   [7:0] grp_dut_perform_conv_1_fu_257_input_V_address1;
wire    grp_dut_perform_conv_1_fu_257_input_V_ce1;
wire   [7:0] grp_dut_perform_conv_1_fu_257_input_V1_address0;
wire    grp_dut_perform_conv_1_fu_257_input_V1_ce0;
wire   [7:0] grp_dut_perform_conv_1_fu_257_input_V1_address1;
wire    grp_dut_perform_conv_1_fu_257_input_V1_ce1;
wire   [7:0] grp_dut_perform_conv_1_fu_257_input_V2_address0;
wire    grp_dut_perform_conv_1_fu_257_input_V2_ce0;
wire   [7:0] grp_dut_perform_conv_1_fu_257_input_V2_address1;
wire    grp_dut_perform_conv_1_fu_257_input_V2_ce1;
wire   [7:0] grp_dut_perform_conv_1_fu_257_input_V3_address0;
wire    grp_dut_perform_conv_1_fu_257_input_V3_ce0;
wire   [7:0] grp_dut_perform_conv_1_fu_257_input_V3_address1;
wire    grp_dut_perform_conv_1_fu_257_input_V3_ce1;
wire   [7:0] grp_dut_perform_conv_1_fu_257_input_V4_address0;
wire    grp_dut_perform_conv_1_fu_257_input_V4_ce0;
wire   [7:0] grp_dut_perform_conv_1_fu_257_input_V4_address1;
wire    grp_dut_perform_conv_1_fu_257_input_V4_ce1;
wire   [8:0] grp_dut_perform_conv_1_fu_257_output_V_address0;
wire    grp_dut_perform_conv_1_fu_257_output_V_ce0;
wire    grp_dut_perform_conv_1_fu_257_output_V_we0;
wire   [13:0] grp_dut_perform_conv_1_fu_257_output_V_d0;
wire   [8:0] grp_dut_perform_conv_1_fu_257_output_V5_address0;
wire    grp_dut_perform_conv_1_fu_257_output_V5_ce0;
wire    grp_dut_perform_conv_1_fu_257_output_V5_we0;
wire   [13:0] grp_dut_perform_conv_1_fu_257_output_V5_d0;
wire   [8:0] grp_dut_perform_conv_1_fu_257_output_V6_address0;
wire    grp_dut_perform_conv_1_fu_257_output_V6_ce0;
wire    grp_dut_perform_conv_1_fu_257_output_V6_we0;
wire   [13:0] grp_dut_perform_conv_1_fu_257_output_V6_d0;
wire    grp_dut_perform_conv_fu_273_ap_start;
wire    grp_dut_perform_conv_fu_273_ap_done;
wire    grp_dut_perform_conv_fu_273_ap_idle;
wire    grp_dut_perform_conv_fu_273_ap_ready;
wire   [8:0] grp_dut_perform_conv_fu_273_input_0_V_address0;
wire    grp_dut_perform_conv_fu_273_input_0_V_ce0;
wire   [8:0] grp_dut_perform_conv_fu_273_input_0_V_address1;
wire    grp_dut_perform_conv_fu_273_input_0_V_ce1;
wire   [8:0] grp_dut_perform_conv_fu_273_input_1_V_address0;
wire    grp_dut_perform_conv_fu_273_input_1_V_ce0;
wire   [8:0] grp_dut_perform_conv_fu_273_input_1_V_address1;
wire    grp_dut_perform_conv_fu_273_input_1_V_ce1;
wire   [8:0] grp_dut_perform_conv_fu_273_input_2_V_address0;
wire    grp_dut_perform_conv_fu_273_input_2_V_ce0;
wire   [8:0] grp_dut_perform_conv_fu_273_input_2_V_address1;
wire    grp_dut_perform_conv_fu_273_input_2_V_ce1;
wire   [7:0] grp_dut_perform_conv_fu_273_output_0_V_address0;
wire    grp_dut_perform_conv_fu_273_output_0_V_ce0;
wire    grp_dut_perform_conv_fu_273_output_0_V_we0;
wire   [13:0] grp_dut_perform_conv_fu_273_output_0_V_d0;
wire   [7:0] grp_dut_perform_conv_fu_273_output_1_V_address0;
wire    grp_dut_perform_conv_fu_273_output_1_V_ce0;
wire    grp_dut_perform_conv_fu_273_output_1_V_we0;
wire   [13:0] grp_dut_perform_conv_fu_273_output_1_V_d0;
wire   [7:0] grp_dut_perform_conv_fu_273_output_2_V_address0;
wire    grp_dut_perform_conv_fu_273_output_2_V_ce0;
wire    grp_dut_perform_conv_fu_273_output_2_V_we0;
wire   [13:0] grp_dut_perform_conv_fu_273_output_2_V_d0;
wire   [7:0] grp_dut_perform_conv_fu_273_output_3_V_address0;
wire    grp_dut_perform_conv_fu_273_output_3_V_ce0;
wire    grp_dut_perform_conv_fu_273_output_3_V_we0;
wire   [13:0] grp_dut_perform_conv_fu_273_output_3_V_d0;
wire   [7:0] grp_dut_perform_conv_fu_273_output_4_V_address0;
wire    grp_dut_perform_conv_fu_273_output_4_V_ce0;
wire    grp_dut_perform_conv_fu_273_output_4_V_we0;
wire   [13:0] grp_dut_perform_conv_fu_273_output_4_V_d0;
reg   [5:0] bvh_d_index_reg_190;
reg   [12:0] phi_mul_reg_201;
reg   [5:0] phi_urem_reg_212;
reg   [9:0] i2_reg_223;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_339;
reg    ap_sig_cseq_ST_st14_fsm_13;
reg    ap_sig_349;
reg   [19:0] phi_mul4_reg_235;
reg   [9:0] phi_urem6_reg_246;
reg    ap_reg_grp_dut_perform_conv_1_fu_257_ap_start;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_363;
reg    ap_reg_grp_dut_perform_conv_fu_273_ap_start;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_397;
wire   [63:0] newIndex_fu_350_p1;
wire   [63:0] newIndex3_fu_429_p1;
wire   [63:0] tmp_16_fu_504_p1;
wire   [2:0] tmp_70_fu_330_p1;
wire   [13:0] tmp_22_cast_fu_323_p1;
wire  signed [31:0] grp_fu_289_p0;
wire   [31:0] index_assign_cast6_fu_292_p1;
wire   [0:0] tmp_fu_308_p3;
wire   [12:0] tmp_s_fu_315_p3;
wire   [4:0] tmp_71_fu_340_p4;
wire   [5:0] next_urem_fu_357_p2;
wire   [0:0] tmp_75_fu_363_p2;
wire   [9:0] next_urem7_fu_389_p2;
wire   [0:0] tmp_72_fu_395_p2;
wire   [7:0] tmp_74_fu_419_p4;
wire   [2:0] tmp_73_fu_409_p1;
wire   [13:0] sel_tmp1_fu_448_p3;
wire   [31:0] grp_fu_289_p1;
wire   [31:0] res_V_1_fu_472_p1;
wire   [7:0] exp_V_fu_476_p4;
wire   [7:0] exp_V_2_fu_486_p2;
reg   [13:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'b1;
#0 ap_reg_grp_dut_perform_conv_1_fu_257_ap_start = 1'b0;
#0 ap_reg_grp_dut_perform_conv_fu_273_ap_start = 1'b0;
end

dut_cnn_xcel_mem_conv1_0_V #(
    .DataWidth( 14 ),
    .AddressRange( 267 ),
    .AddressWidth( 9 ))
mem_conv1_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mem_conv1_0_V_address0),
    .ce0(mem_conv1_0_V_ce0),
    .we0(mem_conv1_0_V_we0),
    .d0(mem_conv1_0_V_d0),
    .q0(mem_conv1_0_V_q0),
    .address1(grp_dut_perform_conv_fu_273_input_0_V_address1),
    .ce1(mem_conv1_0_V_ce1),
    .q1(mem_conv1_0_V_q1)
);

dut_cnn_xcel_mem_conv1_0_V #(
    .DataWidth( 14 ),
    .AddressRange( 267 ),
    .AddressWidth( 9 ))
mem_conv1_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mem_conv1_1_V_address0),
    .ce0(mem_conv1_1_V_ce0),
    .we0(mem_conv1_1_V_we0),
    .d0(mem_conv1_1_V_d0),
    .q0(mem_conv1_1_V_q0),
    .address1(grp_dut_perform_conv_fu_273_input_1_V_address1),
    .ce1(mem_conv1_1_V_ce1),
    .q1(mem_conv1_1_V_q1)
);

dut_cnn_xcel_mem_conv1_2_V #(
    .DataWidth( 14 ),
    .AddressRange( 266 ),
    .AddressWidth( 9 ))
mem_conv1_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mem_conv1_2_V_address0),
    .ce0(mem_conv1_2_V_ce0),
    .we0(mem_conv1_2_V_we0),
    .d0(mem_conv1_2_V_d0),
    .q0(mem_conv1_2_V_q0),
    .address1(grp_dut_perform_conv_fu_273_input_2_V_address1),
    .ce1(mem_conv1_2_V_ce1),
    .q1(mem_conv1_2_V_q1)
);

dut_cnn_xcel_mem_conv2_0_V #(
    .DataWidth( 14 ),
    .AddressRange( 160 ),
    .AddressWidth( 8 ))
mem_conv2_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mem_conv2_0_V_address0),
    .ce0(mem_conv2_0_V_ce0),
    .we0(grp_dut_perform_conv_fu_273_output_0_V_we0),
    .d0(grp_dut_perform_conv_fu_273_output_0_V_d0),
    .q0(mem_conv2_0_V_q0),
    .address1(grp_dut_perform_conv_1_fu_257_input_V_address1),
    .ce1(mem_conv2_0_V_ce1),
    .q1(mem_conv2_0_V_q1)
);

dut_cnn_xcel_mem_conv2_0_V #(
    .DataWidth( 14 ),
    .AddressRange( 160 ),
    .AddressWidth( 8 ))
mem_conv2_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mem_conv2_1_V_address0),
    .ce0(mem_conv2_1_V_ce0),
    .we0(grp_dut_perform_conv_fu_273_output_1_V_we0),
    .d0(grp_dut_perform_conv_fu_273_output_1_V_d0),
    .q0(mem_conv2_1_V_q0),
    .address1(grp_dut_perform_conv_1_fu_257_input_V1_address1),
    .ce1(mem_conv2_1_V_ce1),
    .q1(mem_conv2_1_V_q1)
);

dut_cnn_xcel_mem_conv2_0_V #(
    .DataWidth( 14 ),
    .AddressRange( 160 ),
    .AddressWidth( 8 ))
mem_conv2_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mem_conv2_2_V_address0),
    .ce0(mem_conv2_2_V_ce0),
    .we0(grp_dut_perform_conv_fu_273_output_2_V_we0),
    .d0(grp_dut_perform_conv_fu_273_output_2_V_d0),
    .q0(mem_conv2_2_V_q0),
    .address1(grp_dut_perform_conv_1_fu_257_input_V2_address1),
    .ce1(mem_conv2_2_V_ce1),
    .q1(mem_conv2_2_V_q1)
);

dut_cnn_xcel_mem_conv2_0_V #(
    .DataWidth( 14 ),
    .AddressRange( 160 ),
    .AddressWidth( 8 ))
mem_conv2_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mem_conv2_3_V_address0),
    .ce0(mem_conv2_3_V_ce0),
    .we0(grp_dut_perform_conv_fu_273_output_3_V_we0),
    .d0(grp_dut_perform_conv_fu_273_output_3_V_d0),
    .q0(mem_conv2_3_V_q0),
    .address1(grp_dut_perform_conv_1_fu_257_input_V3_address1),
    .ce1(mem_conv2_3_V_ce1),
    .q1(mem_conv2_3_V_q1)
);

dut_cnn_xcel_mem_conv2_0_V #(
    .DataWidth( 14 ),
    .AddressRange( 160 ),
    .AddressWidth( 8 ))
mem_conv2_4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mem_conv2_4_V_address0),
    .ce0(mem_conv2_4_V_ce0),
    .we0(grp_dut_perform_conv_fu_273_output_4_V_we0),
    .d0(grp_dut_perform_conv_fu_273_output_4_V_d0),
    .q0(mem_conv2_4_V_q0),
    .address1(grp_dut_perform_conv_1_fu_257_input_V4_address1),
    .ce1(mem_conv2_4_V_ce1),
    .q1(mem_conv2_4_V_q1)
);

dut_perform_conv_1 grp_dut_perform_conv_1_fu_257(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dut_perform_conv_1_fu_257_ap_start),
    .ap_done(grp_dut_perform_conv_1_fu_257_ap_done),
    .ap_idle(grp_dut_perform_conv_1_fu_257_ap_idle),
    .ap_ready(grp_dut_perform_conv_1_fu_257_ap_ready),
    .input_V_address0(grp_dut_perform_conv_1_fu_257_input_V_address0),
    .input_V_ce0(grp_dut_perform_conv_1_fu_257_input_V_ce0),
    .input_V_q0(mem_conv2_0_V_q0),
    .input_V_address1(grp_dut_perform_conv_1_fu_257_input_V_address1),
    .input_V_ce1(grp_dut_perform_conv_1_fu_257_input_V_ce1),
    .input_V_q1(mem_conv2_0_V_q1),
    .input_V1_address0(grp_dut_perform_conv_1_fu_257_input_V1_address0),
    .input_V1_ce0(grp_dut_perform_conv_1_fu_257_input_V1_ce0),
    .input_V1_q0(mem_conv2_1_V_q0),
    .input_V1_address1(grp_dut_perform_conv_1_fu_257_input_V1_address1),
    .input_V1_ce1(grp_dut_perform_conv_1_fu_257_input_V1_ce1),
    .input_V1_q1(mem_conv2_1_V_q1),
    .input_V2_address0(grp_dut_perform_conv_1_fu_257_input_V2_address0),
    .input_V2_ce0(grp_dut_perform_conv_1_fu_257_input_V2_ce0),
    .input_V2_q0(mem_conv2_2_V_q0),
    .input_V2_address1(grp_dut_perform_conv_1_fu_257_input_V2_address1),
    .input_V2_ce1(grp_dut_perform_conv_1_fu_257_input_V2_ce1),
    .input_V2_q1(mem_conv2_2_V_q1),
    .input_V3_address0(grp_dut_perform_conv_1_fu_257_input_V3_address0),
    .input_V3_ce0(grp_dut_perform_conv_1_fu_257_input_V3_ce0),
    .input_V3_q0(mem_conv2_3_V_q0),
    .input_V3_address1(grp_dut_perform_conv_1_fu_257_input_V3_address1),
    .input_V3_ce1(grp_dut_perform_conv_1_fu_257_input_V3_ce1),
    .input_V3_q1(mem_conv2_3_V_q1),
    .input_V4_address0(grp_dut_perform_conv_1_fu_257_input_V4_address0),
    .input_V4_ce0(grp_dut_perform_conv_1_fu_257_input_V4_ce0),
    .input_V4_q0(mem_conv2_4_V_q0),
    .input_V4_address1(grp_dut_perform_conv_1_fu_257_input_V4_address1),
    .input_V4_ce1(grp_dut_perform_conv_1_fu_257_input_V4_ce1),
    .input_V4_q1(mem_conv2_4_V_q1),
    .output_V_address0(grp_dut_perform_conv_1_fu_257_output_V_address0),
    .output_V_ce0(grp_dut_perform_conv_1_fu_257_output_V_ce0),
    .output_V_we0(grp_dut_perform_conv_1_fu_257_output_V_we0),
    .output_V_d0(grp_dut_perform_conv_1_fu_257_output_V_d0),
    .output_V_q0(mem_conv1_0_V_q0),
    .output_V5_address0(grp_dut_perform_conv_1_fu_257_output_V5_address0),
    .output_V5_ce0(grp_dut_perform_conv_1_fu_257_output_V5_ce0),
    .output_V5_we0(grp_dut_perform_conv_1_fu_257_output_V5_we0),
    .output_V5_d0(grp_dut_perform_conv_1_fu_257_output_V5_d0),
    .output_V5_q0(mem_conv1_1_V_q0),
    .output_V6_address0(grp_dut_perform_conv_1_fu_257_output_V6_address0),
    .output_V6_ce0(grp_dut_perform_conv_1_fu_257_output_V6_ce0),
    .output_V6_we0(grp_dut_perform_conv_1_fu_257_output_V6_we0),
    .output_V6_d0(grp_dut_perform_conv_1_fu_257_output_V6_d0),
    .output_V6_q0(mem_conv1_2_V_q0)
);

dut_perform_conv grp_dut_perform_conv_fu_273(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dut_perform_conv_fu_273_ap_start),
    .ap_done(grp_dut_perform_conv_fu_273_ap_done),
    .ap_idle(grp_dut_perform_conv_fu_273_ap_idle),
    .ap_ready(grp_dut_perform_conv_fu_273_ap_ready),
    .input_0_V_address0(grp_dut_perform_conv_fu_273_input_0_V_address0),
    .input_0_V_ce0(grp_dut_perform_conv_fu_273_input_0_V_ce0),
    .input_0_V_q0(mem_conv1_0_V_q0),
    .input_0_V_address1(grp_dut_perform_conv_fu_273_input_0_V_address1),
    .input_0_V_ce1(grp_dut_perform_conv_fu_273_input_0_V_ce1),
    .input_0_V_q1(mem_conv1_0_V_q1),
    .input_1_V_address0(grp_dut_perform_conv_fu_273_input_1_V_address0),
    .input_1_V_ce0(grp_dut_perform_conv_fu_273_input_1_V_ce0),
    .input_1_V_q0(mem_conv1_1_V_q0),
    .input_1_V_address1(grp_dut_perform_conv_fu_273_input_1_V_address1),
    .input_1_V_ce1(grp_dut_perform_conv_fu_273_input_1_V_ce1),
    .input_1_V_q1(mem_conv1_1_V_q1),
    .input_2_V_address0(grp_dut_perform_conv_fu_273_input_2_V_address0),
    .input_2_V_ce0(grp_dut_perform_conv_fu_273_input_2_V_ce0),
    .input_2_V_q0(mem_conv1_2_V_q0),
    .input_2_V_address1(grp_dut_perform_conv_fu_273_input_2_V_address1),
    .input_2_V_ce1(grp_dut_perform_conv_fu_273_input_2_V_ce1),
    .input_2_V_q1(mem_conv1_2_V_q1),
    .output_0_V_address0(grp_dut_perform_conv_fu_273_output_0_V_address0),
    .output_0_V_ce0(grp_dut_perform_conv_fu_273_output_0_V_ce0),
    .output_0_V_we0(grp_dut_perform_conv_fu_273_output_0_V_we0),
    .output_0_V_d0(grp_dut_perform_conv_fu_273_output_0_V_d0),
    .output_0_V_q0(mem_conv2_0_V_q0),
    .output_1_V_address0(grp_dut_perform_conv_fu_273_output_1_V_address0),
    .output_1_V_ce0(grp_dut_perform_conv_fu_273_output_1_V_ce0),
    .output_1_V_we0(grp_dut_perform_conv_fu_273_output_1_V_we0),
    .output_1_V_d0(grp_dut_perform_conv_fu_273_output_1_V_d0),
    .output_1_V_q0(mem_conv2_1_V_q0),
    .output_2_V_address0(grp_dut_perform_conv_fu_273_output_2_V_address0),
    .output_2_V_ce0(grp_dut_perform_conv_fu_273_output_2_V_ce0),
    .output_2_V_we0(grp_dut_perform_conv_fu_273_output_2_V_we0),
    .output_2_V_d0(grp_dut_perform_conv_fu_273_output_2_V_d0),
    .output_2_V_q0(mem_conv2_2_V_q0),
    .output_3_V_address0(grp_dut_perform_conv_fu_273_output_3_V_address0),
    .output_3_V_ce0(grp_dut_perform_conv_fu_273_output_3_V_ce0),
    .output_3_V_we0(grp_dut_perform_conv_fu_273_output_3_V_we0),
    .output_3_V_d0(grp_dut_perform_conv_fu_273_output_3_V_d0),
    .output_3_V_q0(mem_conv2_3_V_q0),
    .output_4_V_address0(grp_dut_perform_conv_fu_273_output_4_V_address0),
    .output_4_V_ce0(grp_dut_perform_conv_fu_273_output_4_V_ce0),
    .output_4_V_we0(grp_dut_perform_conv_fu_273_output_4_V_we0),
    .output_4_V_d0(grp_dut_perform_conv_fu_273_output_4_V_d0),
    .output_4_V_q0(mem_conv2_4_V_q0)
);

dut_sitofp_32s_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
dut_sitofp_32s_32_6_U94(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_289_p0),
    .ce(1'b1),
    .dout(grp_fu_289_p1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_dut_perform_conv_1_fu_257_ap_start <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_st4_fsm_3)) begin
            ap_reg_grp_dut_perform_conv_1_fu_257_ap_start <= 1'b1;
        end else if ((1'b1 == grp_dut_perform_conv_1_fu_257_ap_ready)) begin
            ap_reg_grp_dut_perform_conv_1_fu_257_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_dut_perform_conv_fu_273_ap_start <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond5_fu_296_p2 == 1'b0))) begin
            ap_reg_grp_dut_perform_conv_fu_273_ap_start <= 1'b1;
        end else if ((1'b1 == grp_dut_perform_conv_fu_273_ap_ready)) begin
            ap_reg_grp_dut_perform_conv_fu_273_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond5_fu_296_p2 == 1'b0))) begin
        bvh_d_index_reg_190 <= i_fu_302_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        bvh_d_index_reg_190 <= ap_const_lv6_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        i2_reg_223 <= i_3_reg_545;
    end else if (((1'b1 == ap_sig_cseq_ST_st5_fsm_4) & ~(1'b0 == grp_dut_perform_conv_1_fu_257_ap_done))) begin
        i2_reg_223 <= ap_const_lv10_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        phi_mul4_reg_235 <= next_mul5_reg_555;
    end else if (((1'b1 == ap_sig_cseq_ST_st5_fsm_4) & ~(1'b0 == grp_dut_perform_conv_1_fu_257_ap_done))) begin
        phi_mul4_reg_235 <= ap_const_lv20_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond5_fu_296_p2 == 1'b0))) begin
        phi_mul_reg_201 <= next_mul_fu_334_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        phi_mul_reg_201 <= ap_const_lv13_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        phi_urem6_reg_246 <= idx_urem8_reg_550;
    end else if (((1'b1 == ap_sig_cseq_ST_st5_fsm_4) & ~(1'b0 == grp_dut_perform_conv_1_fu_257_ap_done))) begin
        phi_urem6_reg_246 <= ap_const_lv10_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond5_fu_296_p2 == 1'b0))) begin
        phi_urem_reg_212 <= idx_urem_fu_369_p3;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        phi_urem_reg_212 <= ap_const_lv6_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        i_3_reg_545 <= i_3_fu_383_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & (1'b0 == exitcond_fu_377_p2))) begin
        idx_urem8_reg_550 <= idx_urem8_fu_401_p3;
        next_mul5_reg_555 <= next_mul5_fu_413_p2;
        sel_tmp2_reg_580 <= sel_tmp2_fu_442_p2;
        sel_tmp_reg_575 <= sel_tmp_fu_436_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        mem_conv1_V_load_phi_reg_585 <= mem_conv1_V_load_phi_fu_455_p3;
        tmp_17_reg_590 <= tmp_17_fu_462_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == tmp_17_reg_590) & (1'b1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        p_Result_s_reg_600 <= p_Result_s_fu_492_p5;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0)) | ((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~(1'b0 == exitcond_fu_377_p2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~(1'b0 == exitcond_fu_377_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_121) begin
        ap_sig_cseq_ST_st13_fsm_12 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_12 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_349) begin
        ap_sig_cseq_ST_st14_fsm_13 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st14_fsm_13 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_31) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_56) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_397) begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_363) begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_339) begin
        ap_sig_cseq_ST_st5_fsm_4 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_73) begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_99) begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_110) begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond5_fu_296_p2 == 1'b0) & (tmp_70_fu_330_p1 == ap_const_lv3_0))) begin
        mem_conv1_0_V_address0 = newIndex_fu_350_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        mem_conv1_0_V_address0 = newIndex3_fu_429_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv1_0_V_address0 = grp_dut_perform_conv_fu_273_input_0_V_address0;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_0_V_address0 = grp_dut_perform_conv_1_fu_257_output_V_address0;
    end else begin
        mem_conv1_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st6_fsm_5) | ((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond5_fu_296_p2 == 1'b0) & (tmp_70_fu_330_p1 == ap_const_lv3_0)))) begin
        mem_conv1_0_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv1_0_V_ce0 = grp_dut_perform_conv_fu_273_input_0_V_ce0;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_0_V_ce0 = grp_dut_perform_conv_1_fu_257_output_V_ce0;
    end else begin
        mem_conv1_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv1_0_V_ce1 = grp_dut_perform_conv_fu_273_input_0_V_ce1;
    end else begin
        mem_conv1_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond5_fu_296_p2 == 1'b0) & (tmp_70_fu_330_p1 == ap_const_lv3_0))) begin
        mem_conv1_0_V_d0 = tmp_22_cast_fu_323_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_0_V_d0 = grp_dut_perform_conv_1_fu_257_output_V_d0;
    end else begin
        mem_conv1_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond5_fu_296_p2 == 1'b0) & (tmp_70_fu_330_p1 == ap_const_lv3_0))) begin
        mem_conv1_0_V_we0 = 1'b1;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_0_V_we0 = grp_dut_perform_conv_1_fu_257_output_V_we0;
    end else begin
        mem_conv1_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond5_fu_296_p2 == 1'b0) & (tmp_70_fu_330_p1 == ap_const_lv3_1))) begin
        mem_conv1_1_V_address0 = newIndex_fu_350_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        mem_conv1_1_V_address0 = newIndex3_fu_429_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv1_1_V_address0 = grp_dut_perform_conv_fu_273_input_1_V_address0;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_1_V_address0 = grp_dut_perform_conv_1_fu_257_output_V5_address0;
    end else begin
        mem_conv1_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st6_fsm_5) | ((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond5_fu_296_p2 == 1'b0) & (tmp_70_fu_330_p1 == ap_const_lv3_1)))) begin
        mem_conv1_1_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv1_1_V_ce0 = grp_dut_perform_conv_fu_273_input_1_V_ce0;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_1_V_ce0 = grp_dut_perform_conv_1_fu_257_output_V5_ce0;
    end else begin
        mem_conv1_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv1_1_V_ce1 = grp_dut_perform_conv_fu_273_input_1_V_ce1;
    end else begin
        mem_conv1_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond5_fu_296_p2 == 1'b0) & (tmp_70_fu_330_p1 == ap_const_lv3_1))) begin
        mem_conv1_1_V_d0 = tmp_22_cast_fu_323_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_1_V_d0 = grp_dut_perform_conv_1_fu_257_output_V5_d0;
    end else begin
        mem_conv1_1_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond5_fu_296_p2 == 1'b0) & (tmp_70_fu_330_p1 == ap_const_lv3_1))) begin
        mem_conv1_1_V_we0 = 1'b1;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_1_V_we0 = grp_dut_perform_conv_1_fu_257_output_V5_we0;
    end else begin
        mem_conv1_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond5_fu_296_p2 == 1'b0) & ~(tmp_70_fu_330_p1 == ap_const_lv3_0) & ~(tmp_70_fu_330_p1 == ap_const_lv3_1))) begin
        mem_conv1_2_V_address0 = newIndex_fu_350_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        mem_conv1_2_V_address0 = newIndex3_fu_429_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv1_2_V_address0 = grp_dut_perform_conv_fu_273_input_2_V_address0;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_2_V_address0 = grp_dut_perform_conv_1_fu_257_output_V6_address0;
    end else begin
        mem_conv1_2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st6_fsm_5) | ((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond5_fu_296_p2 == 1'b0) & ~(tmp_70_fu_330_p1 == ap_const_lv3_0) & ~(tmp_70_fu_330_p1 == ap_const_lv3_1)))) begin
        mem_conv1_2_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv1_2_V_ce0 = grp_dut_perform_conv_fu_273_input_2_V_ce0;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_2_V_ce0 = grp_dut_perform_conv_1_fu_257_output_V6_ce0;
    end else begin
        mem_conv1_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv1_2_V_ce1 = grp_dut_perform_conv_fu_273_input_2_V_ce1;
    end else begin
        mem_conv1_2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond5_fu_296_p2 == 1'b0) & ~(tmp_70_fu_330_p1 == ap_const_lv3_0) & ~(tmp_70_fu_330_p1 == ap_const_lv3_1))) begin
        mem_conv1_2_V_d0 = tmp_22_cast_fu_323_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_2_V_d0 = grp_dut_perform_conv_1_fu_257_output_V6_d0;
    end else begin
        mem_conv1_2_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond5_fu_296_p2 == 1'b0) & ~(tmp_70_fu_330_p1 == ap_const_lv3_0) & ~(tmp_70_fu_330_p1 == ap_const_lv3_1))) begin
        mem_conv1_2_V_we0 = 1'b1;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_2_V_we0 = grp_dut_perform_conv_1_fu_257_output_V6_we0;
    end else begin
        mem_conv1_2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv2_0_V_address0 = grp_dut_perform_conv_fu_273_output_0_V_address0;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv2_0_V_address0 = grp_dut_perform_conv_1_fu_257_input_V_address0;
    end else begin
        mem_conv2_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv2_0_V_ce0 = grp_dut_perform_conv_fu_273_output_0_V_ce0;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv2_0_V_ce0 = grp_dut_perform_conv_1_fu_257_input_V_ce0;
    end else begin
        mem_conv2_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv2_0_V_ce1 = grp_dut_perform_conv_1_fu_257_input_V_ce1;
    end else begin
        mem_conv2_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv2_1_V_address0 = grp_dut_perform_conv_fu_273_output_1_V_address0;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv2_1_V_address0 = grp_dut_perform_conv_1_fu_257_input_V1_address0;
    end else begin
        mem_conv2_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv2_1_V_ce0 = grp_dut_perform_conv_fu_273_output_1_V_ce0;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv2_1_V_ce0 = grp_dut_perform_conv_1_fu_257_input_V1_ce0;
    end else begin
        mem_conv2_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv2_1_V_ce1 = grp_dut_perform_conv_1_fu_257_input_V1_ce1;
    end else begin
        mem_conv2_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv2_2_V_address0 = grp_dut_perform_conv_fu_273_output_2_V_address0;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv2_2_V_address0 = grp_dut_perform_conv_1_fu_257_input_V2_address0;
    end else begin
        mem_conv2_2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv2_2_V_ce0 = grp_dut_perform_conv_fu_273_output_2_V_ce0;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv2_2_V_ce0 = grp_dut_perform_conv_1_fu_257_input_V2_ce0;
    end else begin
        mem_conv2_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv2_2_V_ce1 = grp_dut_perform_conv_1_fu_257_input_V2_ce1;
    end else begin
        mem_conv2_2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv2_3_V_address0 = grp_dut_perform_conv_fu_273_output_3_V_address0;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv2_3_V_address0 = grp_dut_perform_conv_1_fu_257_input_V3_address0;
    end else begin
        mem_conv2_3_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv2_3_V_ce0 = grp_dut_perform_conv_fu_273_output_3_V_ce0;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv2_3_V_ce0 = grp_dut_perform_conv_1_fu_257_input_V3_ce0;
    end else begin
        mem_conv2_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv2_3_V_ce1 = grp_dut_perform_conv_1_fu_257_input_V3_ce1;
    end else begin
        mem_conv2_3_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv2_4_V_address0 = grp_dut_perform_conv_fu_273_output_4_V_address0;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv2_4_V_address0 = grp_dut_perform_conv_1_fu_257_input_V4_address0;
    end else begin
        mem_conv2_4_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv2_4_V_ce0 = grp_dut_perform_conv_fu_273_output_4_V_ce0;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv2_4_V_ce0 = grp_dut_perform_conv_1_fu_257_input_V4_ce0;
    end else begin
        mem_conv2_4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv2_4_V_ce1 = grp_dut_perform_conv_1_fu_257_input_V4_ce1;
    end else begin
        mem_conv2_4_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        output_V_ce0 = 1'b1;
    end else begin
        output_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        output_V_we0 = 1'b1;
    end else begin
        output_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            if ((exitcond5_fu_296_p2 == 1'b0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st3_fsm_2 : begin
            if (~(1'b0 == grp_dut_perform_conv_fu_273_ap_done)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st4_fsm_3 : begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : begin
            if (~(1'b0 == grp_dut_perform_conv_1_fu_257_ap_done)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        end
        ap_ST_st6_fsm_5 : begin
            if (~(1'b0 == exitcond_fu_377_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        end
        ap_ST_st7_fsm_6 : begin
            ap_NS_fsm = ap_ST_st8_fsm_7;
        end
        ap_ST_st8_fsm_7 : begin
            ap_NS_fsm = ap_ST_st9_fsm_8;
        end
        ap_ST_st9_fsm_8 : begin
            ap_NS_fsm = ap_ST_st10_fsm_9;
        end
        ap_ST_st10_fsm_9 : begin
            ap_NS_fsm = ap_ST_st11_fsm_10;
        end
        ap_ST_st11_fsm_10 : begin
            ap_NS_fsm = ap_ST_st12_fsm_11;
        end
        ap_ST_st12_fsm_11 : begin
            ap_NS_fsm = ap_ST_st13_fsm_12;
        end
        ap_ST_st13_fsm_12 : begin
            ap_NS_fsm = ap_ST_st14_fsm_13;
        end
        ap_ST_st14_fsm_13 : begin
            ap_NS_fsm = ap_ST_st6_fsm_5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    ap_sig_110 = (1'b1 == ap_CS_fsm[ap_const_lv32_7]);
end

always @ (*) begin
    ap_sig_121 = (1'b1 == ap_CS_fsm[ap_const_lv32_C]);
end

always @ (*) begin
    ap_sig_31 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_339 = (1'b1 == ap_CS_fsm[ap_const_lv32_4]);
end

always @ (*) begin
    ap_sig_349 = (1'b1 == ap_CS_fsm[ap_const_lv32_D]);
end

always @ (*) begin
    ap_sig_363 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_397 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_56 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_73 = (1'b1 == ap_CS_fsm[ap_const_lv32_5]);
end

always @ (*) begin
    ap_sig_99 = (1'b1 == ap_CS_fsm[ap_const_lv32_6]);
end

assign exitcond5_fu_296_p2 = ((bvh_d_index_reg_190 == ap_const_lv6_31) ? 1'b1 : 1'b0);

assign exitcond_fu_377_p2 = ((i2_reg_223 == ap_const_lv10_240) ? 1'b1 : 1'b0);

assign exp_V_2_fu_486_p2 = ($signed(ap_const_lv8_F4) + $signed(exp_V_fu_476_p4));

assign exp_V_fu_476_p4 = {{res_V_1_fu_472_p1[ap_const_lv32_1E : ap_const_lv32_17]}};

assign grp_dut_perform_conv_1_fu_257_ap_start = ap_reg_grp_dut_perform_conv_1_fu_257_ap_start;

assign grp_dut_perform_conv_fu_273_ap_start = ap_reg_grp_dut_perform_conv_fu_273_ap_start;

assign grp_fu_289_p0 = $signed(mem_conv1_V_load_phi_reg_585);

assign i_3_fu_383_p2 = (i2_reg_223 + ap_const_lv10_1);

assign i_fu_302_p2 = (bvh_d_index_reg_190 + ap_const_lv6_1);

assign idx_urem8_fu_401_p3 = ((tmp_72_fu_395_p2[0:0] === 1'b1) ? next_urem7_fu_389_p2 : ap_const_lv10_0);

assign idx_urem_fu_369_p3 = ((tmp_75_fu_363_p2[0:0] === 1'b1) ? next_urem_fu_357_p2 : ap_const_lv6_0);

assign index_assign_cast6_fu_292_p1 = bvh_d_index_reg_190;

assign mem_conv1_V_load_phi_fu_455_p3 = ((sel_tmp2_reg_580[0:0] === 1'b1) ? mem_conv1_1_V_q0 : sel_tmp1_fu_448_p3);

assign newIndex3_fu_429_p1 = tmp_74_fu_419_p4;

assign newIndex_fu_350_p1 = tmp_71_fu_340_p4;

assign next_mul5_fu_413_p2 = (ap_const_lv20_556 + phi_mul4_reg_235);

assign next_mul_fu_334_p2 = (ap_const_lv13_56 + phi_mul_reg_201);

assign next_urem7_fu_389_p2 = (ap_const_lv10_1 + phi_urem6_reg_246);

assign next_urem_fu_357_p2 = (phi_urem_reg_212 + ap_const_lv6_1);

assign output_V_address0 = tmp_16_fu_504_p1;

assign output_V_d0 = ((tmp_17_reg_590[0:0] === 1'b1) ? ap_const_lv32_0 : p_Result_s_reg_600);

assign p_Result_s_fu_492_p5 = {{res_V_1_fu_472_p1[32'd31 : 32'd31]}, {exp_V_2_fu_486_p2}, {res_V_1_fu_472_p1[32'd22 : 32'd0]}};

assign res_V_1_fu_472_p1 = grp_fu_289_p1;

assign sel_tmp1_fu_448_p3 = ((sel_tmp_reg_575[0:0] === 1'b1) ? mem_conv1_0_V_q0 : mem_conv1_2_V_q0);

assign sel_tmp2_fu_442_p2 = ((tmp_73_fu_409_p1 == ap_const_lv3_1) ? 1'b1 : 1'b0);

assign sel_tmp_fu_436_p2 = ((tmp_73_fu_409_p1 == ap_const_lv3_0) ? 1'b1 : 1'b0);

assign tmp_16_fu_504_p1 = i2_reg_223;

assign tmp_17_fu_462_p2 = ((mem_conv1_V_load_phi_fu_455_p3 == ap_const_lv14_0) ? 1'b1 : 1'b0);

assign tmp_22_cast_fu_323_p1 = tmp_s_fu_315_p3;

assign tmp_70_fu_330_p1 = phi_urem_reg_212[2:0];

assign tmp_71_fu_340_p4 = {{phi_mul_reg_201[ap_const_lv32_C : ap_const_lv32_8]}};

assign tmp_72_fu_395_p2 = ((next_urem7_fu_389_p2 < ap_const_lv10_3) ? 1'b1 : 1'b0);

assign tmp_73_fu_409_p1 = phi_urem6_reg_246[2:0];

assign tmp_74_fu_419_p4 = {{phi_mul4_reg_235[ap_const_lv32_13 : ap_const_lv32_C]}};

assign tmp_75_fu_363_p2 = ((next_urem_fu_357_p2 < ap_const_lv6_3) ? 1'b1 : 1'b0);

assign tmp_fu_308_p3 = input_V[index_assign_cast6_fu_292_p1];

assign tmp_s_fu_315_p3 = {{tmp_fu_308_p3}, {ap_const_lv12_0}};

endmodule //dut_cnn_xcel
