lappend pragmaStatus0 {pragma "UNROLL" source "/home/clc288/lab4/ecelinux/layer.cpp" location "perform_conv/Lc" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "UNROLL" source "/home/clc288/lab4/ecelinux/layer.cpp" location "perform_conv/Lr" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "PIPELINE" source "/home/clc288/lab4/ecelinux/layer.cpp" location "perform_conv/Lm" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "ARRAY_PARTITION" source "/home/clc288/lab4/ecelinux/layer.cpp" location "cnn_xcel" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'cnn_xcel' does not exist in any synthesis source file." variable "mem_conv2"}
lappend pragmaStatus4 {pragma "ARRAY_PARTITION" source "/home/clc288/lab4/ecelinux/layer.cpp" location "cnn_xcel" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'cnn_xcel' does not exist in any synthesis source file." variable "mem_conv1"}
lappend pragmaStatus0 {pragma "UNROLL" source "/home/clc288/lab4/ecelinux/cnn.cpp" location "perform_conv/Lc" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'perform_conv' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "UNROLL" source "/home/clc288/lab4/ecelinux/cnn.cpp" location "perform_conv/Lr" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'perform_conv' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "PIPELINE" source "/home/clc288/lab4/ecelinux/cnn.cpp" location "perform_conv/Lm" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'perform_conv' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "ARRAY_PARTITION" source "/home/clc288/lab4/ecelinux/cnn.cpp" location "cnn_xcel" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "mem_conv2"}
lappend pragmaStatus4 {pragma "ARRAY_PARTITION" source "/home/clc288/lab4/ecelinux/cnn.cpp" location "cnn_xcel" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "mem_conv1"}
